package com.mapper;

import com.model.Bumen;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BumenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bumen
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bumenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bumen
     *
     * @mbggenerated
     */
    int insert(Bumen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bumen
     *
     * @mbggenerated
     */
    Bumen selectByPrimaryKey(Integer bumenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bumen
     *
     * @mbggenerated
     */
    List<Bumen> selectAll(@Param("bumen")Bumen record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bumen
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bumen record);
}