package com.mapper;

import com.model.Buyuan;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BuyuanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyuan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer buyuanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyuan
     *
     * @mbggenerated
     */
    int insert(Buyuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyuan
     *
     * @mbggenerated
     */
    Buyuan selectByPrimaryKey(Integer buyuanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyuan
     *
     * @mbggenerated
     */
    List<Buyuan> selectAll(@Param("buyuan")Buyuan record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyuan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Buyuan record);
}