package com.mapper;

import com.model.Jcdaohang;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface JcdaohangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer jcdaohangId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbggenerated
     */
    int insert(Jcdaohang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbggenerated
     */
    Jcdaohang selectByPrimaryKey(Integer jcdaohangId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbggenerated
     */
    List<Jcdaohang> selectAll(@Param("jcdaohang")Jcdaohang record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jcdaohang
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Jcdaohang record);
}