package com.mapper;

import com.model.Rizhi;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RizhiMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_rizhi
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer rizhiId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_rizhi
	 * @mbggenerated
	 */
	int insert(Rizhi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_rizhi
	 * @mbggenerated
	 */
	Rizhi selectByPrimaryKey(Integer rizhiId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_rizhi
	 * @mbggenerated
	 */
	List<Rizhi> selectAll(@Param("rizhi")Rizhi record,@Param("page")int page,@Param("rows")int rows);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_rizhi
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Rizhi record);
}