package com.mapper;

import com.model.Shuju;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ShujuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shujuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbggenerated
     */
    int insert(Shuju record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbggenerated
     */
    Shuju selectByPrimaryKey(Integer shujuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbggenerated
     */
	List<Shuju> selectAll(@Param("shuju")Shuju record,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate, @Param("sdate1")String sdate1, @Param("edate1")String edate1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shuju
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shuju record);
}