package com.mapper;

import com.model.Sjleixing;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SjleixingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sjleixingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbggenerated
     */
    int insert(Sjleixing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbggenerated
     */
    Sjleixing selectByPrimaryKey(Integer sjleixingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbggenerated
     */
    List<Sjleixing> selectAll(@Param("sjleixing")Sjleixing record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjleixing
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sjleixing record);
}