package com.mapper;

import com.model.Sjpinglun;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SjpinglunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjpinglun
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sjpinglunId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjpinglun
     *
     * @mbggenerated
     */
    int insert(Sjpinglun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjpinglun
     *
     * @mbggenerated
     */
    Sjpinglun selectByPrimaryKey(Integer sjpinglunId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjpinglun
     *
     * @mbggenerated
     */
	List<Sjpinglun> selectAll(@Param("sjpinglun")Sjpinglun record,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate, @Param("sdate1")String sdate1, @Param("edate1")String edate1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjpinglun
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sjpinglun record);
}