package com.mapper;

import com.model.Sjxingtai;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SjxingtaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxingtai
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sjxingtaiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxingtai
     *
     * @mbggenerated
     */
    int insert(Sjxingtai record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxingtai
     *
     * @mbggenerated
     */
    Sjxingtai selectByPrimaryKey(Integer sjxingtaiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxingtai
     *
     * @mbggenerated
     */
    List<Sjxingtai> selectAll(@Param("sjxingtai")Sjxingtai record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sjxingtai
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sjxingtai record);
}