package com.mapper;

import com.model.Uxtype;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UxtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uxtype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uxtypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uxtype
     *
     * @mbggenerated
     */
    int insert(Uxtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uxtype
     *
     * @mbggenerated
     */
    Uxtype selectByPrimaryKey(Integer uxtypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uxtype
     *
     * @mbggenerated
     */
    List<Uxtype> selectAll(@Param("uxtype")Uxtype record,@Param("page")int page,@Param("rows")int rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uxtype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Uxtype record);
}