package com.mapper;

import com.model.Uyijian;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UyijianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uyijian
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uyijianId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uyijian
     *
     * @mbggenerated
     */
    int insert(Uyijian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uyijian
     *
     * @mbggenerated
     */
    Uyijian selectByPrimaryKey(Integer uyijianId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uyijian
     *
     * @mbggenerated
     */
    List<Uyijian> selectAll(@Param("uyijian")Uyijian record,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uyijian
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Uyijian record);
}