package com.mapper;

import com.model.Yonghu;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface YonghuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer yonghuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbggenerated
     */
    int insert(Yonghu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbggenerated
     */
    Yonghu selectByPrimaryKey(Integer yonghuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbggenerated
     */
	List<Yonghu> selectAll(@Param("yonghu")Yonghu record,@Param("yonghuName")String yonghuName,@Param("page")int page,@Param("rows")int rows, @Param("sdate")String sdate, @Param("edate")String edate, @Param("sdate1")String sdate1, @Param("edate1")String edate1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yonghu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yonghu record);
}