package com.model;

public class Bumen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenMark
     *
     * @mbggenerated
     */
    private String bumenMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenMark1
     *
     * @mbggenerated
     */
    private String bumenMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenMark2
     *
     * @mbggenerated
     */
    private String bumenMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenType
     *
     * @mbggenerated
     */
    private Integer bumenType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenType1
     *
     * @mbggenerated
     */
    private Integer bumenType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenType2
     *
     * @mbggenerated
     */
    private Integer bumenType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenDouble
     *
     * @mbggenerated
     */
    private Double bumenDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenDouble1
     *
     * @mbggenerated
     */
    private Double bumenDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.bumenDouble2
     *
     * @mbggenerated
     */
    private Double bumenDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bumen.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenId
     *
     * @return the value of t_bumen.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenId
     *
     * @param bumenId the value for t_bumen.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenName
     *
     * @return the value of t_bumen.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenName
     *
     * @param bumenName the value for t_bumen.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenMark
     *
     * @return the value of t_bumen.bumenMark
     *
     * @mbggenerated
     */
    public String getBumenMark() {
        return bumenMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenMark
     *
     * @param bumenMark the value for t_bumen.bumenMark
     *
     * @mbggenerated
     */
    public void setBumenMark(String bumenMark) {
        this.bumenMark = bumenMark == null ? null : bumenMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenMark1
     *
     * @return the value of t_bumen.bumenMark1
     *
     * @mbggenerated
     */
    public String getBumenMark1() {
        return bumenMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenMark1
     *
     * @param bumenMark1 the value for t_bumen.bumenMark1
     *
     * @mbggenerated
     */
    public void setBumenMark1(String bumenMark1) {
        this.bumenMark1 = bumenMark1 == null ? null : bumenMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenMark2
     *
     * @return the value of t_bumen.bumenMark2
     *
     * @mbggenerated
     */
    public String getBumenMark2() {
        return bumenMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenMark2
     *
     * @param bumenMark2 the value for t_bumen.bumenMark2
     *
     * @mbggenerated
     */
    public void setBumenMark2(String bumenMark2) {
        this.bumenMark2 = bumenMark2 == null ? null : bumenMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenType
     *
     * @return the value of t_bumen.bumenType
     *
     * @mbggenerated
     */
    public Integer getBumenType() {
        return bumenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenType
     *
     * @param bumenType the value for t_bumen.bumenType
     *
     * @mbggenerated
     */
    public void setBumenType(Integer bumenType) {
        this.bumenType = bumenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenType1
     *
     * @return the value of t_bumen.bumenType1
     *
     * @mbggenerated
     */
    public Integer getBumenType1() {
        return bumenType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenType1
     *
     * @param bumenType1 the value for t_bumen.bumenType1
     *
     * @mbggenerated
     */
    public void setBumenType1(Integer bumenType1) {
        this.bumenType1 = bumenType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenType2
     *
     * @return the value of t_bumen.bumenType2
     *
     * @mbggenerated
     */
    public Integer getBumenType2() {
        return bumenType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenType2
     *
     * @param bumenType2 the value for t_bumen.bumenType2
     *
     * @mbggenerated
     */
    public void setBumenType2(Integer bumenType2) {
        this.bumenType2 = bumenType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenDouble
     *
     * @return the value of t_bumen.bumenDouble
     *
     * @mbggenerated
     */
    public Double getBumenDouble() {
        return bumenDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenDouble
     *
     * @param bumenDouble the value for t_bumen.bumenDouble
     *
     * @mbggenerated
     */
    public void setBumenDouble(Double bumenDouble) {
        this.bumenDouble = bumenDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenDouble1
     *
     * @return the value of t_bumen.bumenDouble1
     *
     * @mbggenerated
     */
    public Double getBumenDouble1() {
        return bumenDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenDouble1
     *
     * @param bumenDouble1 the value for t_bumen.bumenDouble1
     *
     * @mbggenerated
     */
    public void setBumenDouble1(Double bumenDouble1) {
        this.bumenDouble1 = bumenDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.bumenDouble2
     *
     * @return the value of t_bumen.bumenDouble2
     *
     * @mbggenerated
     */
    public Double getBumenDouble2() {
        return bumenDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.bumenDouble2
     *
     * @param bumenDouble2 the value for t_bumen.bumenDouble2
     *
     * @mbggenerated
     */
    public void setBumenDouble2(Double bumenDouble2) {
        this.bumenDouble2 = bumenDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.buyuanId
     *
     * @return the value of t_bumen.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.buyuanId
     *
     * @param buyuanId the value for t_bumen.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bumen.buyuanName
     *
     * @return the value of t_bumen.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bumen.buyuanName
     *
     * @param buyuanName the value for t_bumen.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }
}