package com.model;

public class Buyuan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanMark
     *
     * @mbggenerated
     */
    private String buyuanMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanMark1
     *
     * @mbggenerated
     */
    private String buyuanMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanMark2
     *
     * @mbggenerated
     */
    private String buyuanMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanType
     *
     * @mbggenerated
     */
    private Integer buyuanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanType1
     *
     * @mbggenerated
     */
    private Integer buyuanType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanType2
     *
     * @mbggenerated
     */
    private Integer buyuanType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanDouble
     *
     * @mbggenerated
     */
    private Double buyuanDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanDouble1
     *
     * @mbggenerated
     */
    private Double buyuanDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyuan.buyuanDouble2
     *
     * @mbggenerated
     */
    private Double buyuanDouble2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanId
     *
     * @return the value of t_buyuan.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanId
     *
     * @param buyuanId the value for t_buyuan.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanName
     *
     * @return the value of t_buyuan.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanName
     *
     * @param buyuanName the value for t_buyuan.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanMark
     *
     * @return the value of t_buyuan.buyuanMark
     *
     * @mbggenerated
     */
    public String getBuyuanMark() {
        return buyuanMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanMark
     *
     * @param buyuanMark the value for t_buyuan.buyuanMark
     *
     * @mbggenerated
     */
    public void setBuyuanMark(String buyuanMark) {
        this.buyuanMark = buyuanMark == null ? null : buyuanMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanMark1
     *
     * @return the value of t_buyuan.buyuanMark1
     *
     * @mbggenerated
     */
    public String getBuyuanMark1() {
        return buyuanMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanMark1
     *
     * @param buyuanMark1 the value for t_buyuan.buyuanMark1
     *
     * @mbggenerated
     */
    public void setBuyuanMark1(String buyuanMark1) {
        this.buyuanMark1 = buyuanMark1 == null ? null : buyuanMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanMark2
     *
     * @return the value of t_buyuan.buyuanMark2
     *
     * @mbggenerated
     */
    public String getBuyuanMark2() {
        return buyuanMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanMark2
     *
     * @param buyuanMark2 the value for t_buyuan.buyuanMark2
     *
     * @mbggenerated
     */
    public void setBuyuanMark2(String buyuanMark2) {
        this.buyuanMark2 = buyuanMark2 == null ? null : buyuanMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanType
     *
     * @return the value of t_buyuan.buyuanType
     *
     * @mbggenerated
     */
    public Integer getBuyuanType() {
        return buyuanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanType
     *
     * @param buyuanType the value for t_buyuan.buyuanType
     *
     * @mbggenerated
     */
    public void setBuyuanType(Integer buyuanType) {
        this.buyuanType = buyuanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanType1
     *
     * @return the value of t_buyuan.buyuanType1
     *
     * @mbggenerated
     */
    public Integer getBuyuanType1() {
        return buyuanType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanType1
     *
     * @param buyuanType1 the value for t_buyuan.buyuanType1
     *
     * @mbggenerated
     */
    public void setBuyuanType1(Integer buyuanType1) {
        this.buyuanType1 = buyuanType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanType2
     *
     * @return the value of t_buyuan.buyuanType2
     *
     * @mbggenerated
     */
    public Integer getBuyuanType2() {
        return buyuanType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanType2
     *
     * @param buyuanType2 the value for t_buyuan.buyuanType2
     *
     * @mbggenerated
     */
    public void setBuyuanType2(Integer buyuanType2) {
        this.buyuanType2 = buyuanType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanDouble
     *
     * @return the value of t_buyuan.buyuanDouble
     *
     * @mbggenerated
     */
    public Double getBuyuanDouble() {
        return buyuanDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanDouble
     *
     * @param buyuanDouble the value for t_buyuan.buyuanDouble
     *
     * @mbggenerated
     */
    public void setBuyuanDouble(Double buyuanDouble) {
        this.buyuanDouble = buyuanDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanDouble1
     *
     * @return the value of t_buyuan.buyuanDouble1
     *
     * @mbggenerated
     */
    public Double getBuyuanDouble1() {
        return buyuanDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanDouble1
     *
     * @param buyuanDouble1 the value for t_buyuan.buyuanDouble1
     *
     * @mbggenerated
     */
    public void setBuyuanDouble1(Double buyuanDouble1) {
        this.buyuanDouble1 = buyuanDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyuan.buyuanDouble2
     *
     * @return the value of t_buyuan.buyuanDouble2
     *
     * @mbggenerated
     */
    public Double getBuyuanDouble2() {
        return buyuanDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyuan.buyuanDouble2
     *
     * @param buyuanDouble2 the value for t_buyuan.buyuanDouble2
     *
     * @mbggenerated
     */
    public void setBuyuanDouble2(Double buyuanDouble2) {
        this.buyuanDouble2 = buyuanDouble2;
    }
}