package com.model;

public class Buzhi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiMark
     *
     * @mbggenerated
     */
    private String buzhiMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiMark1
     *
     * @mbggenerated
     */
    private String buzhiMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiMark2
     *
     * @mbggenerated
     */
    private String buzhiMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiType
     *
     * @mbggenerated
     */
    private Integer buzhiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiType1
     *
     * @mbggenerated
     */
    private Integer buzhiType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiType2
     *
     * @mbggenerated
     */
    private Integer buzhiType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiDouble
     *
     * @mbggenerated
     */
    private Double buzhiDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiDouble1
     *
     * @mbggenerated
     */
    private Double buzhiDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buzhiDouble2
     *
     * @mbggenerated
     */
    private Double buzhiDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buzhi.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiId
     *
     * @return the value of t_buzhi.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiId
     *
     * @param buzhiId the value for t_buzhi.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiName
     *
     * @return the value of t_buzhi.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiName
     *
     * @param buzhiName the value for t_buzhi.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiMark
     *
     * @return the value of t_buzhi.buzhiMark
     *
     * @mbggenerated
     */
    public String getBuzhiMark() {
        return buzhiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiMark
     *
     * @param buzhiMark the value for t_buzhi.buzhiMark
     *
     * @mbggenerated
     */
    public void setBuzhiMark(String buzhiMark) {
        this.buzhiMark = buzhiMark == null ? null : buzhiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiMark1
     *
     * @return the value of t_buzhi.buzhiMark1
     *
     * @mbggenerated
     */
    public String getBuzhiMark1() {
        return buzhiMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiMark1
     *
     * @param buzhiMark1 the value for t_buzhi.buzhiMark1
     *
     * @mbggenerated
     */
    public void setBuzhiMark1(String buzhiMark1) {
        this.buzhiMark1 = buzhiMark1 == null ? null : buzhiMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiMark2
     *
     * @return the value of t_buzhi.buzhiMark2
     *
     * @mbggenerated
     */
    public String getBuzhiMark2() {
        return buzhiMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiMark2
     *
     * @param buzhiMark2 the value for t_buzhi.buzhiMark2
     *
     * @mbggenerated
     */
    public void setBuzhiMark2(String buzhiMark2) {
        this.buzhiMark2 = buzhiMark2 == null ? null : buzhiMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiType
     *
     * @return the value of t_buzhi.buzhiType
     *
     * @mbggenerated
     */
    public Integer getBuzhiType() {
        return buzhiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiType
     *
     * @param buzhiType the value for t_buzhi.buzhiType
     *
     * @mbggenerated
     */
    public void setBuzhiType(Integer buzhiType) {
        this.buzhiType = buzhiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiType1
     *
     * @return the value of t_buzhi.buzhiType1
     *
     * @mbggenerated
     */
    public Integer getBuzhiType1() {
        return buzhiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiType1
     *
     * @param buzhiType1 the value for t_buzhi.buzhiType1
     *
     * @mbggenerated
     */
    public void setBuzhiType1(Integer buzhiType1) {
        this.buzhiType1 = buzhiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiType2
     *
     * @return the value of t_buzhi.buzhiType2
     *
     * @mbggenerated
     */
    public Integer getBuzhiType2() {
        return buzhiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiType2
     *
     * @param buzhiType2 the value for t_buzhi.buzhiType2
     *
     * @mbggenerated
     */
    public void setBuzhiType2(Integer buzhiType2) {
        this.buzhiType2 = buzhiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiDouble
     *
     * @return the value of t_buzhi.buzhiDouble
     *
     * @mbggenerated
     */
    public Double getBuzhiDouble() {
        return buzhiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiDouble
     *
     * @param buzhiDouble the value for t_buzhi.buzhiDouble
     *
     * @mbggenerated
     */
    public void setBuzhiDouble(Double buzhiDouble) {
        this.buzhiDouble = buzhiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiDouble1
     *
     * @return the value of t_buzhi.buzhiDouble1
     *
     * @mbggenerated
     */
    public Double getBuzhiDouble1() {
        return buzhiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiDouble1
     *
     * @param buzhiDouble1 the value for t_buzhi.buzhiDouble1
     *
     * @mbggenerated
     */
    public void setBuzhiDouble1(Double buzhiDouble1) {
        this.buzhiDouble1 = buzhiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buzhiDouble2
     *
     * @return the value of t_buzhi.buzhiDouble2
     *
     * @mbggenerated
     */
    public Double getBuzhiDouble2() {
        return buzhiDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buzhiDouble2
     *
     * @param buzhiDouble2 the value for t_buzhi.buzhiDouble2
     *
     * @mbggenerated
     */
    public void setBuzhiDouble2(Double buzhiDouble2) {
        this.buzhiDouble2 = buzhiDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buyuanId
     *
     * @return the value of t_buzhi.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buyuanId
     *
     * @param buyuanId the value for t_buzhi.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.buyuanName
     *
     * @return the value of t_buzhi.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.buyuanName
     *
     * @param buyuanName the value for t_buzhi.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.bumenId
     *
     * @return the value of t_buzhi.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.bumenId
     *
     * @param bumenId the value for t_buzhi.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buzhi.bumenName
     *
     * @return the value of t_buzhi.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buzhi.bumenName
     *
     * @param bumenName the value for t_buzhi.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }
}