package com.model;

import java.util.Date;

public class Ggpinglun {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggpinglunId
     *
     * @mbggenerated
     */
    private Integer ggpinglunId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggpinglunName
     *
     * @mbggenerated
     */
    private String ggpinglunName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggpinglunMark
     *
     * @mbggenerated
     */
    private String ggpinglunMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggpinglunDate
     *
     * @mbggenerated
     */
    private Date ggpinglunDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggpinglunDate1
     *
     * @mbggenerated
     */
    private Date ggpinglunDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggpinglunType
     *
     * @mbggenerated
     */
    private Integer ggpinglunType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggpinglunType1
     *
     * @mbggenerated
     */
    private Integer ggpinglunType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggpinglunImg
     *
     * @mbggenerated
     */
    private String ggpinglunImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggpinglunImgName
     *
     * @mbggenerated
     */
    private String ggpinglunImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.gonggaoId
     *
     * @mbggenerated
     */
    private Integer gonggaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.gonggaoName
     *
     * @mbggenerated
     */
    private String gonggaoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggtypeId
     *
     * @mbggenerated
     */
    private Integer ggtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.ggtypeName
     *
     * @mbggenerated
     */
    private String ggtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.byumenId
     *
     * @mbggenerated
     */
    private Integer byumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.byumenName
     *
     * @mbggenerated
     */
    private String byumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.byuyuanId
     *
     * @mbggenerated
     */
    private Integer byuyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.byuyuanName
     *
     * @mbggenerated
     */
    private String byuyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.byuzhiId
     *
     * @mbggenerated
     */
    private Integer byuzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.byuzhiName
     *
     * @mbggenerated
     */
    private String byuzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggpinglun.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggpinglunId
     *
     * @return the value of t_ggpinglun.ggpinglunId
     *
     * @mbggenerated
     */
    public Integer getGgpinglunId() {
        return ggpinglunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggpinglunId
     *
     * @param ggpinglunId the value for t_ggpinglun.ggpinglunId
     *
     * @mbggenerated
     */
    public void setGgpinglunId(Integer ggpinglunId) {
        this.ggpinglunId = ggpinglunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggpinglunName
     *
     * @return the value of t_ggpinglun.ggpinglunName
     *
     * @mbggenerated
     */
    public String getGgpinglunName() {
        return ggpinglunName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggpinglunName
     *
     * @param ggpinglunName the value for t_ggpinglun.ggpinglunName
     *
     * @mbggenerated
     */
    public void setGgpinglunName(String ggpinglunName) {
        this.ggpinglunName = ggpinglunName == null ? null : ggpinglunName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggpinglunMark
     *
     * @return the value of t_ggpinglun.ggpinglunMark
     *
     * @mbggenerated
     */
    public String getGgpinglunMark() {
        return ggpinglunMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggpinglunMark
     *
     * @param ggpinglunMark the value for t_ggpinglun.ggpinglunMark
     *
     * @mbggenerated
     */
    public void setGgpinglunMark(String ggpinglunMark) {
        this.ggpinglunMark = ggpinglunMark == null ? null : ggpinglunMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggpinglunDate
     *
     * @return the value of t_ggpinglun.ggpinglunDate
     *
     * @mbggenerated
     */
    public Date getGgpinglunDate() {
        return ggpinglunDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggpinglunDate
     *
     * @param ggpinglunDate the value for t_ggpinglun.ggpinglunDate
     *
     * @mbggenerated
     */
    public void setGgpinglunDate(Date ggpinglunDate) {
        this.ggpinglunDate = ggpinglunDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggpinglunDate1
     *
     * @return the value of t_ggpinglun.ggpinglunDate1
     *
     * @mbggenerated
     */
    public Date getGgpinglunDate1() {
        return ggpinglunDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggpinglunDate1
     *
     * @param ggpinglunDate1 the value for t_ggpinglun.ggpinglunDate1
     *
     * @mbggenerated
     */
    public void setGgpinglunDate1(Date ggpinglunDate1) {
        this.ggpinglunDate1 = ggpinglunDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggpinglunType
     *
     * @return the value of t_ggpinglun.ggpinglunType
     *
     * @mbggenerated
     */
    public Integer getGgpinglunType() {
        return ggpinglunType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggpinglunType
     *
     * @param ggpinglunType the value for t_ggpinglun.ggpinglunType
     *
     * @mbggenerated
     */
    public void setGgpinglunType(Integer ggpinglunType) {
        this.ggpinglunType = ggpinglunType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggpinglunType1
     *
     * @return the value of t_ggpinglun.ggpinglunType1
     *
     * @mbggenerated
     */
    public Integer getGgpinglunType1() {
        return ggpinglunType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggpinglunType1
     *
     * @param ggpinglunType1 the value for t_ggpinglun.ggpinglunType1
     *
     * @mbggenerated
     */
    public void setGgpinglunType1(Integer ggpinglunType1) {
        this.ggpinglunType1 = ggpinglunType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggpinglunImg
     *
     * @return the value of t_ggpinglun.ggpinglunImg
     *
     * @mbggenerated
     */
    public String getGgpinglunImg() {
        return ggpinglunImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggpinglunImg
     *
     * @param ggpinglunImg the value for t_ggpinglun.ggpinglunImg
     *
     * @mbggenerated
     */
    public void setGgpinglunImg(String ggpinglunImg) {
        this.ggpinglunImg = ggpinglunImg == null ? null : ggpinglunImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggpinglunImgName
     *
     * @return the value of t_ggpinglun.ggpinglunImgName
     *
     * @mbggenerated
     */
    public String getGgpinglunImgName() {
        return ggpinglunImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggpinglunImgName
     *
     * @param ggpinglunImgName the value for t_ggpinglun.ggpinglunImgName
     *
     * @mbggenerated
     */
    public void setGgpinglunImgName(String ggpinglunImgName) {
        this.ggpinglunImgName = ggpinglunImgName == null ? null : ggpinglunImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.gonggaoId
     *
     * @return the value of t_ggpinglun.gonggaoId
     *
     * @mbggenerated
     */
    public Integer getGonggaoId() {
        return gonggaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.gonggaoId
     *
     * @param gonggaoId the value for t_ggpinglun.gonggaoId
     *
     * @mbggenerated
     */
    public void setGonggaoId(Integer gonggaoId) {
        this.gonggaoId = gonggaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.gonggaoName
     *
     * @return the value of t_ggpinglun.gonggaoName
     *
     * @mbggenerated
     */
    public String getGonggaoName() {
        return gonggaoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.gonggaoName
     *
     * @param gonggaoName the value for t_ggpinglun.gonggaoName
     *
     * @mbggenerated
     */
    public void setGonggaoName(String gonggaoName) {
        this.gonggaoName = gonggaoName == null ? null : gonggaoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggtypeId
     *
     * @return the value of t_ggpinglun.ggtypeId
     *
     * @mbggenerated
     */
    public Integer getGgtypeId() {
        return ggtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggtypeId
     *
     * @param ggtypeId the value for t_ggpinglun.ggtypeId
     *
     * @mbggenerated
     */
    public void setGgtypeId(Integer ggtypeId) {
        this.ggtypeId = ggtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.ggtypeName
     *
     * @return the value of t_ggpinglun.ggtypeName
     *
     * @mbggenerated
     */
    public String getGgtypeName() {
        return ggtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.ggtypeName
     *
     * @param ggtypeName the value for t_ggpinglun.ggtypeName
     *
     * @mbggenerated
     */
    public void setGgtypeName(String ggtypeName) {
        this.ggtypeName = ggtypeName == null ? null : ggtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.userId
     *
     * @return the value of t_ggpinglun.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.userId
     *
     * @param userId the value for t_ggpinglun.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.userName
     *
     * @return the value of t_ggpinglun.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.userName
     *
     * @param userName the value for t_ggpinglun.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.bumenId
     *
     * @return the value of t_ggpinglun.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.bumenId
     *
     * @param bumenId the value for t_ggpinglun.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.bumenName
     *
     * @return the value of t_ggpinglun.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.bumenName
     *
     * @param bumenName the value for t_ggpinglun.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.buyuanId
     *
     * @return the value of t_ggpinglun.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.buyuanId
     *
     * @param buyuanId the value for t_ggpinglun.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.buyuanName
     *
     * @return the value of t_ggpinglun.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.buyuanName
     *
     * @param buyuanName the value for t_ggpinglun.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.yonghuId
     *
     * @return the value of t_ggpinglun.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.yonghuId
     *
     * @param yonghuId the value for t_ggpinglun.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.yonghuName
     *
     * @return the value of t_ggpinglun.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.yonghuName
     *
     * @param yonghuName the value for t_ggpinglun.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.byumenId
     *
     * @return the value of t_ggpinglun.byumenId
     *
     * @mbggenerated
     */
    public Integer getByumenId() {
        return byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.byumenId
     *
     * @param byumenId the value for t_ggpinglun.byumenId
     *
     * @mbggenerated
     */
    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.byumenName
     *
     * @return the value of t_ggpinglun.byumenName
     *
     * @mbggenerated
     */
    public String getByumenName() {
        return byumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.byumenName
     *
     * @param byumenName the value for t_ggpinglun.byumenName
     *
     * @mbggenerated
     */
    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.byuyuanId
     *
     * @return the value of t_ggpinglun.byuyuanId
     *
     * @mbggenerated
     */
    public Integer getByuyuanId() {
        return byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.byuyuanId
     *
     * @param byuyuanId the value for t_ggpinglun.byuyuanId
     *
     * @mbggenerated
     */
    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.byuyuanName
     *
     * @return the value of t_ggpinglun.byuyuanName
     *
     * @mbggenerated
     */
    public String getByuyuanName() {
        return byuyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.byuyuanName
     *
     * @param byuyuanName the value for t_ggpinglun.byuyuanName
     *
     * @mbggenerated
     */
    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.buzhiId
     *
     * @return the value of t_ggpinglun.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.buzhiId
     *
     * @param buzhiId the value for t_ggpinglun.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.buzhiName
     *
     * @return the value of t_ggpinglun.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.buzhiName
     *
     * @param buzhiName the value for t_ggpinglun.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.roleId
     *
     * @return the value of t_ggpinglun.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.roleId
     *
     * @param roleId the value for t_ggpinglun.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.roleName
     *
     * @return the value of t_ggpinglun.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.roleName
     *
     * @param roleName the value for t_ggpinglun.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.byuzhiId
     *
     * @return the value of t_ggpinglun.byuzhiId
     *
     * @mbggenerated
     */
    public Integer getByuzhiId() {
        return byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.byuzhiId
     *
     * @param byuzhiId the value for t_ggpinglun.byuzhiId
     *
     * @mbggenerated
     */
    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.byuzhiName
     *
     * @return the value of t_ggpinglun.byuzhiName
     *
     * @mbggenerated
     */
    public String getByuzhiName() {
        return byuzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.byuzhiName
     *
     * @param byuzhiName the value for t_ggpinglun.byuzhiName
     *
     * @mbggenerated
     */
    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.yhroleId
     *
     * @return the value of t_ggpinglun.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.yhroleId
     *
     * @param yhroleId the value for t_ggpinglun.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggpinglun.yhroleName
     *
     * @return the value of t_ggpinglun.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggpinglun.yhroleName
     *
     * @param yhroleName the value for t_ggpinglun.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}