package com.model;

public class Ggtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggtype.ggtypeId
     *
     * @mbggenerated
     */
    private Integer ggtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggtype.ggtypeName
     *
     * @mbggenerated
     */
    private String ggtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ggtype.ggtypeMark
     *
     * @mbggenerated
     */
    private String ggtypeMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggtype.ggtypeId
     *
     * @return the value of t_ggtype.ggtypeId
     *
     * @mbggenerated
     */
    public Integer getGgtypeId() {
        return ggtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggtype.ggtypeId
     *
     * @param ggtypeId the value for t_ggtype.ggtypeId
     *
     * @mbggenerated
     */
    public void setGgtypeId(Integer ggtypeId) {
        this.ggtypeId = ggtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggtype.ggtypeName
     *
     * @return the value of t_ggtype.ggtypeName
     *
     * @mbggenerated
     */
    public String getGgtypeName() {
        return ggtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggtype.ggtypeName
     *
     * @param ggtypeName the value for t_ggtype.ggtypeName
     *
     * @mbggenerated
     */
    public void setGgtypeName(String ggtypeName) {
        this.ggtypeName = ggtypeName == null ? null : ggtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ggtype.ggtypeMark
     *
     * @return the value of t_ggtype.ggtypeMark
     *
     * @mbggenerated
     */
    public String getGgtypeMark() {
        return ggtypeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ggtype.ggtypeMark
     *
     * @param ggtypeMark the value for t_ggtype.ggtypeMark
     *
     * @mbggenerated
     */
    public void setGgtypeMark(String ggtypeMark) {
        this.ggtypeMark = ggtypeMark == null ? null : ggtypeMark.trim();
    }
}