package com.model;

import java.util.Date;

public class Gonggao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gonggao.gonggaoId
     *
     * @mbggenerated
     */
    private Integer gonggaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gonggao.gonggaoName
     *
     * @mbggenerated
     */
    private String gonggaoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gonggao.gonggaoMark
     *
     * @mbggenerated
     */
    private String gonggaoMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gonggao.gonggaoImg
     *
     * @mbggenerated
     */
    private String gonggaoImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gonggao.gonggaoImgName
     *
     * @mbggenerated
     */
    private String gonggaoImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gonggao.gonggaoDate
     *
     * @mbggenerated
     */
    private Date gonggaoDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gonggao.ggtypeId
     *
     * @mbggenerated
     */
    private Integer ggtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gonggao.ggtypeName
     *
     * @mbggenerated
     */
    private String ggtypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gonggao.gonggaoId
     *
     * @return the value of t_gonggao.gonggaoId
     *
     * @mbggenerated
     */
    public Integer getGonggaoId() {
        return gonggaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gonggao.gonggaoId
     *
     * @param gonggaoId the value for t_gonggao.gonggaoId
     *
     * @mbggenerated
     */
    public void setGonggaoId(Integer gonggaoId) {
        this.gonggaoId = gonggaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gonggao.gonggaoName
     *
     * @return the value of t_gonggao.gonggaoName
     *
     * @mbggenerated
     */
    public String getGonggaoName() {
        return gonggaoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gonggao.gonggaoName
     *
     * @param gonggaoName the value for t_gonggao.gonggaoName
     *
     * @mbggenerated
     */
    public void setGonggaoName(String gonggaoName) {
        this.gonggaoName = gonggaoName == null ? null : gonggaoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gonggao.gonggaoMark
     *
     * @return the value of t_gonggao.gonggaoMark
     *
     * @mbggenerated
     */
    public String getGonggaoMark() {
        return gonggaoMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gonggao.gonggaoMark
     *
     * @param gonggaoMark the value for t_gonggao.gonggaoMark
     *
     * @mbggenerated
     */
    public void setGonggaoMark(String gonggaoMark) {
        this.gonggaoMark = gonggaoMark == null ? null : gonggaoMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gonggao.gonggaoImg
     *
     * @return the value of t_gonggao.gonggaoImg
     *
     * @mbggenerated
     */
    public String getGonggaoImg() {
        return gonggaoImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gonggao.gonggaoImg
     *
     * @param gonggaoImg the value for t_gonggao.gonggaoImg
     *
     * @mbggenerated
     */
    public void setGonggaoImg(String gonggaoImg) {
        this.gonggaoImg = gonggaoImg == null ? null : gonggaoImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gonggao.gonggaoImgName
     *
     * @return the value of t_gonggao.gonggaoImgName
     *
     * @mbggenerated
     */
    public String getGonggaoImgName() {
        return gonggaoImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gonggao.gonggaoImgName
     *
     * @param gonggaoImgName the value for t_gonggao.gonggaoImgName
     *
     * @mbggenerated
     */
    public void setGonggaoImgName(String gonggaoImgName) {
        this.gonggaoImgName = gonggaoImgName == null ? null : gonggaoImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gonggao.gonggaoDate
     *
     * @return the value of t_gonggao.gonggaoDate
     *
     * @mbggenerated
     */
    public Date getGonggaoDate() {
        return gonggaoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gonggao.gonggaoDate
     *
     * @param gonggaoDate the value for t_gonggao.gonggaoDate
     *
     * @mbggenerated
     */
    public void setGonggaoDate(Date gonggaoDate) {
        this.gonggaoDate = gonggaoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gonggao.ggtypeId
     *
     * @return the value of t_gonggao.ggtypeId
     *
     * @mbggenerated
     */
    public Integer getGgtypeId() {
        return ggtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gonggao.ggtypeId
     *
     * @param ggtypeId the value for t_gonggao.ggtypeId
     *
     * @mbggenerated
     */
    public void setGgtypeId(Integer ggtypeId) {
        this.ggtypeId = ggtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gonggao.ggtypeName
     *
     * @return the value of t_gonggao.ggtypeName
     *
     * @mbggenerated
     */
    public String getGgtypeName() {
        return ggtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gonggao.ggtypeName
     *
     * @param ggtypeName the value for t_gonggao.ggtypeName
     *
     * @mbggenerated
     */
    public void setGgtypeName(String ggtypeName) {
        this.ggtypeName = ggtypeName == null ? null : ggtypeName.trim();
    }
}