package com.model;

public class Jcbiaoti {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiId
     *
     * @mbggenerated
     */
    private Integer jcbiaotiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiName
     *
     * @mbggenerated
     */
    private String jcbiaotiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiNeirong
     *
     * @mbggenerated
     */
    private String jcbiaotiNeirong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiMark
     *
     * @mbggenerated
     */
    private String jcbiaotiMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiMark1
     *
     * @mbggenerated
     */
    private String jcbiaotiMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiMark2
     *
     * @mbggenerated
     */
    private String jcbiaotiMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiPaixu
     *
     * @mbggenerated
     */
    private Integer jcbiaotiPaixu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiType
     *
     * @mbggenerated
     */
    private Integer jcbiaotiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiType1
     *
     * @mbggenerated
     */
    private Integer jcbiaotiType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcbiaoti.jcbiaotiType2
     *
     * @mbggenerated
     */
    private Integer jcbiaotiType2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiId
     *
     * @return the value of t_jcbiaoti.jcbiaotiId
     *
     * @mbggenerated
     */
    public Integer getJcbiaotiId() {
        return jcbiaotiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiId
     *
     * @param jcbiaotiId the value for t_jcbiaoti.jcbiaotiId
     *
     * @mbggenerated
     */
    public void setJcbiaotiId(Integer jcbiaotiId) {
        this.jcbiaotiId = jcbiaotiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiName
     *
     * @return the value of t_jcbiaoti.jcbiaotiName
     *
     * @mbggenerated
     */
    public String getJcbiaotiName() {
        return jcbiaotiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiName
     *
     * @param jcbiaotiName the value for t_jcbiaoti.jcbiaotiName
     *
     * @mbggenerated
     */
    public void setJcbiaotiName(String jcbiaotiName) {
        this.jcbiaotiName = jcbiaotiName == null ? null : jcbiaotiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiNeirong
     *
     * @return the value of t_jcbiaoti.jcbiaotiNeirong
     *
     * @mbggenerated
     */
    public String getJcbiaotiNeirong() {
        return jcbiaotiNeirong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiNeirong
     *
     * @param jcbiaotiNeirong the value for t_jcbiaoti.jcbiaotiNeirong
     *
     * @mbggenerated
     */
    public void setJcbiaotiNeirong(String jcbiaotiNeirong) {
        this.jcbiaotiNeirong = jcbiaotiNeirong == null ? null : jcbiaotiNeirong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiMark
     *
     * @return the value of t_jcbiaoti.jcbiaotiMark
     *
     * @mbggenerated
     */
    public String getJcbiaotiMark() {
        return jcbiaotiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiMark
     *
     * @param jcbiaotiMark the value for t_jcbiaoti.jcbiaotiMark
     *
     * @mbggenerated
     */
    public void setJcbiaotiMark(String jcbiaotiMark) {
        this.jcbiaotiMark = jcbiaotiMark == null ? null : jcbiaotiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiMark1
     *
     * @return the value of t_jcbiaoti.jcbiaotiMark1
     *
     * @mbggenerated
     */
    public String getJcbiaotiMark1() {
        return jcbiaotiMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiMark1
     *
     * @param jcbiaotiMark1 the value for t_jcbiaoti.jcbiaotiMark1
     *
     * @mbggenerated
     */
    public void setJcbiaotiMark1(String jcbiaotiMark1) {
        this.jcbiaotiMark1 = jcbiaotiMark1 == null ? null : jcbiaotiMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiMark2
     *
     * @return the value of t_jcbiaoti.jcbiaotiMark2
     *
     * @mbggenerated
     */
    public String getJcbiaotiMark2() {
        return jcbiaotiMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiMark2
     *
     * @param jcbiaotiMark2 the value for t_jcbiaoti.jcbiaotiMark2
     *
     * @mbggenerated
     */
    public void setJcbiaotiMark2(String jcbiaotiMark2) {
        this.jcbiaotiMark2 = jcbiaotiMark2 == null ? null : jcbiaotiMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiPaixu
     *
     * @return the value of t_jcbiaoti.jcbiaotiPaixu
     *
     * @mbggenerated
     */
    public Integer getJcbiaotiPaixu() {
        return jcbiaotiPaixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiPaixu
     *
     * @param jcbiaotiPaixu the value for t_jcbiaoti.jcbiaotiPaixu
     *
     * @mbggenerated
     */
    public void setJcbiaotiPaixu(Integer jcbiaotiPaixu) {
        this.jcbiaotiPaixu = jcbiaotiPaixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiType
     *
     * @return the value of t_jcbiaoti.jcbiaotiType
     *
     * @mbggenerated
     */
    public Integer getJcbiaotiType() {
        return jcbiaotiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiType
     *
     * @param jcbiaotiType the value for t_jcbiaoti.jcbiaotiType
     *
     * @mbggenerated
     */
    public void setJcbiaotiType(Integer jcbiaotiType) {
        this.jcbiaotiType = jcbiaotiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiType1
     *
     * @return the value of t_jcbiaoti.jcbiaotiType1
     *
     * @mbggenerated
     */
    public Integer getJcbiaotiType1() {
        return jcbiaotiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiType1
     *
     * @param jcbiaotiType1 the value for t_jcbiaoti.jcbiaotiType1
     *
     * @mbggenerated
     */
    public void setJcbiaotiType1(Integer jcbiaotiType1) {
        this.jcbiaotiType1 = jcbiaotiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcbiaoti.jcbiaotiType2
     *
     * @return the value of t_jcbiaoti.jcbiaotiType2
     *
     * @mbggenerated
     */
    public Integer getJcbiaotiType2() {
        return jcbiaotiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcbiaoti.jcbiaotiType2
     *
     * @param jcbiaotiType2 the value for t_jcbiaoti.jcbiaotiType2
     *
     * @mbggenerated
     */
    public void setJcbiaotiType2(Integer jcbiaotiType2) {
        this.jcbiaotiType2 = jcbiaotiType2;
    }
}