package com.model;

public class Jcdaohang {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangId
     *
     * @mbggenerated
     */
    private Integer jcdaohangId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangName
     *
     * @mbggenerated
     */
    private String jcdaohangName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangNeirong
     *
     * @mbggenerated
     */
    private String jcdaohangNeirong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangMark
     *
     * @mbggenerated
     */
    private String jcdaohangMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangMark1
     *
     * @mbggenerated
     */
    private String jcdaohangMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangMark2
     *
     * @mbggenerated
     */
    private String jcdaohangMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangPaixu
     *
     * @mbggenerated
     */
    private Integer jcdaohangPaixu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangType
     *
     * @mbggenerated
     */
    private Integer jcdaohangType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangType1
     *
     * @mbggenerated
     */
    private Integer jcdaohangType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcdaohangType2
     *
     * @mbggenerated
     */
    private Integer jcdaohangType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcbiaotiId
     *
     * @mbggenerated
     */
    private Integer jcbiaotiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcdaohang.jcbiaotiName
     *
     * @mbggenerated
     */
    private String jcbiaotiName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangId
     *
     * @return the value of t_jcdaohang.jcdaohangId
     *
     * @mbggenerated
     */
    public Integer getJcdaohangId() {
        return jcdaohangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangId
     *
     * @param jcdaohangId the value for t_jcdaohang.jcdaohangId
     *
     * @mbggenerated
     */
    public void setJcdaohangId(Integer jcdaohangId) {
        this.jcdaohangId = jcdaohangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangName
     *
     * @return the value of t_jcdaohang.jcdaohangName
     *
     * @mbggenerated
     */
    public String getJcdaohangName() {
        return jcdaohangName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangName
     *
     * @param jcdaohangName the value for t_jcdaohang.jcdaohangName
     *
     * @mbggenerated
     */
    public void setJcdaohangName(String jcdaohangName) {
        this.jcdaohangName = jcdaohangName == null ? null : jcdaohangName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangNeirong
     *
     * @return the value of t_jcdaohang.jcdaohangNeirong
     *
     * @mbggenerated
     */
    public String getJcdaohangNeirong() {
        return jcdaohangNeirong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangNeirong
     *
     * @param jcdaohangNeirong the value for t_jcdaohang.jcdaohangNeirong
     *
     * @mbggenerated
     */
    public void setJcdaohangNeirong(String jcdaohangNeirong) {
        this.jcdaohangNeirong = jcdaohangNeirong == null ? null : jcdaohangNeirong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangMark
     *
     * @return the value of t_jcdaohang.jcdaohangMark
     *
     * @mbggenerated
     */
    public String getJcdaohangMark() {
        return jcdaohangMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangMark
     *
     * @param jcdaohangMark the value for t_jcdaohang.jcdaohangMark
     *
     * @mbggenerated
     */
    public void setJcdaohangMark(String jcdaohangMark) {
        this.jcdaohangMark = jcdaohangMark == null ? null : jcdaohangMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangMark1
     *
     * @return the value of t_jcdaohang.jcdaohangMark1
     *
     * @mbggenerated
     */
    public String getJcdaohangMark1() {
        return jcdaohangMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangMark1
     *
     * @param jcdaohangMark1 the value for t_jcdaohang.jcdaohangMark1
     *
     * @mbggenerated
     */
    public void setJcdaohangMark1(String jcdaohangMark1) {
        this.jcdaohangMark1 = jcdaohangMark1 == null ? null : jcdaohangMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangMark2
     *
     * @return the value of t_jcdaohang.jcdaohangMark2
     *
     * @mbggenerated
     */
    public String getJcdaohangMark2() {
        return jcdaohangMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangMark2
     *
     * @param jcdaohangMark2 the value for t_jcdaohang.jcdaohangMark2
     *
     * @mbggenerated
     */
    public void setJcdaohangMark2(String jcdaohangMark2) {
        this.jcdaohangMark2 = jcdaohangMark2 == null ? null : jcdaohangMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangPaixu
     *
     * @return the value of t_jcdaohang.jcdaohangPaixu
     *
     * @mbggenerated
     */
    public Integer getJcdaohangPaixu() {
        return jcdaohangPaixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangPaixu
     *
     * @param jcdaohangPaixu the value for t_jcdaohang.jcdaohangPaixu
     *
     * @mbggenerated
     */
    public void setJcdaohangPaixu(Integer jcdaohangPaixu) {
        this.jcdaohangPaixu = jcdaohangPaixu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangType
     *
     * @return the value of t_jcdaohang.jcdaohangType
     *
     * @mbggenerated
     */
    public Integer getJcdaohangType() {
        return jcdaohangType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangType
     *
     * @param jcdaohangType the value for t_jcdaohang.jcdaohangType
     *
     * @mbggenerated
     */
    public void setJcdaohangType(Integer jcdaohangType) {
        this.jcdaohangType = jcdaohangType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangType1
     *
     * @return the value of t_jcdaohang.jcdaohangType1
     *
     * @mbggenerated
     */
    public Integer getJcdaohangType1() {
        return jcdaohangType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangType1
     *
     * @param jcdaohangType1 the value for t_jcdaohang.jcdaohangType1
     *
     * @mbggenerated
     */
    public void setJcdaohangType1(Integer jcdaohangType1) {
        this.jcdaohangType1 = jcdaohangType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcdaohangType2
     *
     * @return the value of t_jcdaohang.jcdaohangType2
     *
     * @mbggenerated
     */
    public Integer getJcdaohangType2() {
        return jcdaohangType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcdaohangType2
     *
     * @param jcdaohangType2 the value for t_jcdaohang.jcdaohangType2
     *
     * @mbggenerated
     */
    public void setJcdaohangType2(Integer jcdaohangType2) {
        this.jcdaohangType2 = jcdaohangType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcbiaotiId
     *
     * @return the value of t_jcdaohang.jcbiaotiId
     *
     * @mbggenerated
     */
    public Integer getJcbiaotiId() {
        return jcbiaotiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcbiaotiId
     *
     * @param jcbiaotiId the value for t_jcdaohang.jcbiaotiId
     *
     * @mbggenerated
     */
    public void setJcbiaotiId(Integer jcbiaotiId) {
        this.jcbiaotiId = jcbiaotiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcdaohang.jcbiaotiName
     *
     * @return the value of t_jcdaohang.jcbiaotiName
     *
     * @mbggenerated
     */
    public String getJcbiaotiName() {
        return jcbiaotiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcdaohang.jcbiaotiName
     *
     * @param jcbiaotiName the value for t_jcdaohang.jcbiaotiName
     *
     * @mbggenerated
     */
    public void setJcbiaotiName(String jcbiaotiName) {
        this.jcbiaotiName = jcbiaotiName == null ? null : jcbiaotiName.trim();
    }
}