package com.model;

public class Jcpeizhi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.jcpeizhiId
     *
     * @mbggenerated
     */
    private Integer jcpeizhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.jcpeizhiName
     *
     * @mbggenerated
     */
    private String jcpeizhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.jcpeizhiNeirong
     *
     * @mbggenerated
     */
    private String jcpeizhiNeirong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.jcpeizhiMark
     *
     * @mbggenerated
     */
    private String jcpeizhiMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.bumenBieming
     *
     * @mbggenerated
     */
    private String bumenBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.buyuanBieming
     *
     * @mbggenerated
     */
    private String buyuanBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.buzhiBieming
     *
     * @mbggenerated
     */
    private String buzhiBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.userBieming
     *
     * @mbggenerated
     */
    private String userBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.uxtypeBieming
     *
     * @mbggenerated
     */
    private String uxtypeBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.uxinxiBieming
     *
     * @mbggenerated
     */
    private String uxinxiBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.uyijianBieming
     *
     * @mbggenerated
     */
    private String uyijianBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.roleBieming
     *
     * @mbggenerated
     */
    private String roleBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.byumenBieming
     *
     * @mbggenerated
     */
    private String byumenBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.byuyuanBieming
     *
     * @mbggenerated
     */
    private String byuyuanBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.byuzhiBieming
     *
     * @mbggenerated
     */
    private String byuzhiBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.yonghuBieming
     *
     * @mbggenerated
     */
    private String yonghuBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.yxtypeBieming
     *
     * @mbggenerated
     */
    private String yxtypeBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.yxinxiBieming
     *
     * @mbggenerated
     */
    private String yxinxiBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.yyijianBieming
     *
     * @mbggenerated
     */
    private String yyijianBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.yhroleBieming
     *
     * @mbggenerated
     */
    private String yhroleBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.ggtypeBieming
     *
     * @mbggenerated
     */
    private String ggtypeBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.gonggaoBieming
     *
     * @mbggenerated
     */
    private String gonggaoBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.ggpinglunBieming
     *
     * @mbggenerated
     */
    private String ggpinglunBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.shujuBieming
     *
     * @mbggenerated
     */
    private String shujuBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.sjduochuBieming
     *
     * @mbggenerated
     */
    private String sjduochuBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.sjjianchuBieming
     *
     * @mbggenerated
     */
    private String sjjianchuBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.sjlaiyuanBieming
     *
     * @mbggenerated
     */
    private String sjlaiyuanBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.sjleixingBieming
     *
     * @mbggenerated
     */
    private String sjleixingBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.sjpinglunBieming
     *
     * @mbggenerated
     */
    private String sjpinglunBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.sjqitaBieming
     *
     * @mbggenerated
     */
    private String sjqitaBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.sjshaochuBieming
     *
     * @mbggenerated
     */
    private String sjshaochuBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.sjxingtaiBieming
     *
     * @mbggenerated
     */
    private String sjxingtaiBieming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.jcpeizhiType
     *
     * @mbggenerated
     */
    private Integer jcpeizhiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.jcpeizhiType1
     *
     * @mbggenerated
     */
    private Integer jcpeizhiType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jcpeizhi.jcpeizhiType2
     *
     * @mbggenerated
     */
    private Integer jcpeizhiType2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.jcpeizhiId
     *
     * @return the value of t_jcpeizhi.jcpeizhiId
     *
     * @mbggenerated
     */
    public Integer getJcpeizhiId() {
        return jcpeizhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.jcpeizhiId
     *
     * @param jcpeizhiId the value for t_jcpeizhi.jcpeizhiId
     *
     * @mbggenerated
     */
    public void setJcpeizhiId(Integer jcpeizhiId) {
        this.jcpeizhiId = jcpeizhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.jcpeizhiName
     *
     * @return the value of t_jcpeizhi.jcpeizhiName
     *
     * @mbggenerated
     */
    public String getJcpeizhiName() {
        return jcpeizhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.jcpeizhiName
     *
     * @param jcpeizhiName the value for t_jcpeizhi.jcpeizhiName
     *
     * @mbggenerated
     */
    public void setJcpeizhiName(String jcpeizhiName) {
        this.jcpeizhiName = jcpeizhiName == null ? null : jcpeizhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.jcpeizhiNeirong
     *
     * @return the value of t_jcpeizhi.jcpeizhiNeirong
     *
     * @mbggenerated
     */
    public String getJcpeizhiNeirong() {
        return jcpeizhiNeirong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.jcpeizhiNeirong
     *
     * @param jcpeizhiNeirong the value for t_jcpeizhi.jcpeizhiNeirong
     *
     * @mbggenerated
     */
    public void setJcpeizhiNeirong(String jcpeizhiNeirong) {
        this.jcpeizhiNeirong = jcpeizhiNeirong == null ? null : jcpeizhiNeirong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.jcpeizhiMark
     *
     * @return the value of t_jcpeizhi.jcpeizhiMark
     *
     * @mbggenerated
     */
    public String getJcpeizhiMark() {
        return jcpeizhiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.jcpeizhiMark
     *
     * @param jcpeizhiMark the value for t_jcpeizhi.jcpeizhiMark
     *
     * @mbggenerated
     */
    public void setJcpeizhiMark(String jcpeizhiMark) {
        this.jcpeizhiMark = jcpeizhiMark == null ? null : jcpeizhiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.bumenBieming
     *
     * @return the value of t_jcpeizhi.bumenBieming
     *
     * @mbggenerated
     */
    public String getBumenBieming() {
        return bumenBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.bumenBieming
     *
     * @param bumenBieming the value for t_jcpeizhi.bumenBieming
     *
     * @mbggenerated
     */
    public void setBumenBieming(String bumenBieming) {
        this.bumenBieming = bumenBieming == null ? null : bumenBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.buyuanBieming
     *
     * @return the value of t_jcpeizhi.buyuanBieming
     *
     * @mbggenerated
     */
    public String getBuyuanBieming() {
        return buyuanBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.buyuanBieming
     *
     * @param buyuanBieming the value for t_jcpeizhi.buyuanBieming
     *
     * @mbggenerated
     */
    public void setBuyuanBieming(String buyuanBieming) {
        this.buyuanBieming = buyuanBieming == null ? null : buyuanBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.buzhiBieming
     *
     * @return the value of t_jcpeizhi.buzhiBieming
     *
     * @mbggenerated
     */
    public String getBuzhiBieming() {
        return buzhiBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.buzhiBieming
     *
     * @param buzhiBieming the value for t_jcpeizhi.buzhiBieming
     *
     * @mbggenerated
     */
    public void setBuzhiBieming(String buzhiBieming) {
        this.buzhiBieming = buzhiBieming == null ? null : buzhiBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.userBieming
     *
     * @return the value of t_jcpeizhi.userBieming
     *
     * @mbggenerated
     */
    public String getUserBieming() {
        return userBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.userBieming
     *
     * @param userBieming the value for t_jcpeizhi.userBieming
     *
     * @mbggenerated
     */
    public void setUserBieming(String userBieming) {
        this.userBieming = userBieming == null ? null : userBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.uxtypeBieming
     *
     * @return the value of t_jcpeizhi.uxtypeBieming
     *
     * @mbggenerated
     */
    public String getUxtypeBieming() {
        return uxtypeBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.uxtypeBieming
     *
     * @param uxtypeBieming the value for t_jcpeizhi.uxtypeBieming
     *
     * @mbggenerated
     */
    public void setUxtypeBieming(String uxtypeBieming) {
        this.uxtypeBieming = uxtypeBieming == null ? null : uxtypeBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.uxinxiBieming
     *
     * @return the value of t_jcpeizhi.uxinxiBieming
     *
     * @mbggenerated
     */
    public String getUxinxiBieming() {
        return uxinxiBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.uxinxiBieming
     *
     * @param uxinxiBieming the value for t_jcpeizhi.uxinxiBieming
     *
     * @mbggenerated
     */
    public void setUxinxiBieming(String uxinxiBieming) {
        this.uxinxiBieming = uxinxiBieming == null ? null : uxinxiBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.uyijianBieming
     *
     * @return the value of t_jcpeizhi.uyijianBieming
     *
     * @mbggenerated
     */
    public String getUyijianBieming() {
        return uyijianBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.uyijianBieming
     *
     * @param uyijianBieming the value for t_jcpeizhi.uyijianBieming
     *
     * @mbggenerated
     */
    public void setUyijianBieming(String uyijianBieming) {
        this.uyijianBieming = uyijianBieming == null ? null : uyijianBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.roleBieming
     *
     * @return the value of t_jcpeizhi.roleBieming
     *
     * @mbggenerated
     */
    public String getRoleBieming() {
        return roleBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.roleBieming
     *
     * @param roleBieming the value for t_jcpeizhi.roleBieming
     *
     * @mbggenerated
     */
    public void setRoleBieming(String roleBieming) {
        this.roleBieming = roleBieming == null ? null : roleBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.byumenBieming
     *
     * @return the value of t_jcpeizhi.byumenBieming
     *
     * @mbggenerated
     */
    public String getByumenBieming() {
        return byumenBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.byumenBieming
     *
     * @param byumenBieming the value for t_jcpeizhi.byumenBieming
     *
     * @mbggenerated
     */
    public void setByumenBieming(String byumenBieming) {
        this.byumenBieming = byumenBieming == null ? null : byumenBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.byuyuanBieming
     *
     * @return the value of t_jcpeizhi.byuyuanBieming
     *
     * @mbggenerated
     */
    public String getByuyuanBieming() {
        return byuyuanBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.byuyuanBieming
     *
     * @param byuyuanBieming the value for t_jcpeizhi.byuyuanBieming
     *
     * @mbggenerated
     */
    public void setByuyuanBieming(String byuyuanBieming) {
        this.byuyuanBieming = byuyuanBieming == null ? null : byuyuanBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.byuzhiBieming
     *
     * @return the value of t_jcpeizhi.byuzhiBieming
     *
     * @mbggenerated
     */
    public String getByuzhiBieming() {
        return byuzhiBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.byuzhiBieming
     *
     * @param byuzhiBieming the value for t_jcpeizhi.byuzhiBieming
     *
     * @mbggenerated
     */
    public void setByuzhiBieming(String byuzhiBieming) {
        this.byuzhiBieming = byuzhiBieming == null ? null : byuzhiBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.yonghuBieming
     *
     * @return the value of t_jcpeizhi.yonghuBieming
     *
     * @mbggenerated
     */
    public String getYonghuBieming() {
        return yonghuBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.yonghuBieming
     *
     * @param yonghuBieming the value for t_jcpeizhi.yonghuBieming
     *
     * @mbggenerated
     */
    public void setYonghuBieming(String yonghuBieming) {
        this.yonghuBieming = yonghuBieming == null ? null : yonghuBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.yxtypeBieming
     *
     * @return the value of t_jcpeizhi.yxtypeBieming
     *
     * @mbggenerated
     */
    public String getYxtypeBieming() {
        return yxtypeBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.yxtypeBieming
     *
     * @param yxtypeBieming the value for t_jcpeizhi.yxtypeBieming
     *
     * @mbggenerated
     */
    public void setYxtypeBieming(String yxtypeBieming) {
        this.yxtypeBieming = yxtypeBieming == null ? null : yxtypeBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.yxinxiBieming
     *
     * @return the value of t_jcpeizhi.yxinxiBieming
     *
     * @mbggenerated
     */
    public String getYxinxiBieming() {
        return yxinxiBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.yxinxiBieming
     *
     * @param yxinxiBieming the value for t_jcpeizhi.yxinxiBieming
     *
     * @mbggenerated
     */
    public void setYxinxiBieming(String yxinxiBieming) {
        this.yxinxiBieming = yxinxiBieming == null ? null : yxinxiBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.yyijianBieming
     *
     * @return the value of t_jcpeizhi.yyijianBieming
     *
     * @mbggenerated
     */
    public String getYyijianBieming() {
        return yyijianBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.yyijianBieming
     *
     * @param yyijianBieming the value for t_jcpeizhi.yyijianBieming
     *
     * @mbggenerated
     */
    public void setYyijianBieming(String yyijianBieming) {
        this.yyijianBieming = yyijianBieming == null ? null : yyijianBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.yhroleBieming
     *
     * @return the value of t_jcpeizhi.yhroleBieming
     *
     * @mbggenerated
     */
    public String getYhroleBieming() {
        return yhroleBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.yhroleBieming
     *
     * @param yhroleBieming the value for t_jcpeizhi.yhroleBieming
     *
     * @mbggenerated
     */
    public void setYhroleBieming(String yhroleBieming) {
        this.yhroleBieming = yhroleBieming == null ? null : yhroleBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.ggtypeBieming
     *
     * @return the value of t_jcpeizhi.ggtypeBieming
     *
     * @mbggenerated
     */
    public String getGgtypeBieming() {
        return ggtypeBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.ggtypeBieming
     *
     * @param ggtypeBieming the value for t_jcpeizhi.ggtypeBieming
     *
     * @mbggenerated
     */
    public void setGgtypeBieming(String ggtypeBieming) {
        this.ggtypeBieming = ggtypeBieming == null ? null : ggtypeBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.gonggaoBieming
     *
     * @return the value of t_jcpeizhi.gonggaoBieming
     *
     * @mbggenerated
     */
    public String getGonggaoBieming() {
        return gonggaoBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.gonggaoBieming
     *
     * @param gonggaoBieming the value for t_jcpeizhi.gonggaoBieming
     *
     * @mbggenerated
     */
    public void setGonggaoBieming(String gonggaoBieming) {
        this.gonggaoBieming = gonggaoBieming == null ? null : gonggaoBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.ggpinglunBieming
     *
     * @return the value of t_jcpeizhi.ggpinglunBieming
     *
     * @mbggenerated
     */
    public String getGgpinglunBieming() {
        return ggpinglunBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.ggpinglunBieming
     *
     * @param ggpinglunBieming the value for t_jcpeizhi.ggpinglunBieming
     *
     * @mbggenerated
     */
    public void setGgpinglunBieming(String ggpinglunBieming) {
        this.ggpinglunBieming = ggpinglunBieming == null ? null : ggpinglunBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.shujuBieming
     *
     * @return the value of t_jcpeizhi.shujuBieming
     *
     * @mbggenerated
     */
    public String getShujuBieming() {
        return shujuBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.shujuBieming
     *
     * @param shujuBieming the value for t_jcpeizhi.shujuBieming
     *
     * @mbggenerated
     */
    public void setShujuBieming(String shujuBieming) {
        this.shujuBieming = shujuBieming == null ? null : shujuBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.sjduochuBieming
     *
     * @return the value of t_jcpeizhi.sjduochuBieming
     *
     * @mbggenerated
     */
    public String getSjduochuBieming() {
        return sjduochuBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.sjduochuBieming
     *
     * @param sjduochuBieming the value for t_jcpeizhi.sjduochuBieming
     *
     * @mbggenerated
     */
    public void setSjduochuBieming(String sjduochuBieming) {
        this.sjduochuBieming = sjduochuBieming == null ? null : sjduochuBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.sjjianchuBieming
     *
     * @return the value of t_jcpeizhi.sjjianchuBieming
     *
     * @mbggenerated
     */
    public String getSjjianchuBieming() {
        return sjjianchuBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.sjjianchuBieming
     *
     * @param sjjianchuBieming the value for t_jcpeizhi.sjjianchuBieming
     *
     * @mbggenerated
     */
    public void setSjjianchuBieming(String sjjianchuBieming) {
        this.sjjianchuBieming = sjjianchuBieming == null ? null : sjjianchuBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.sjlaiyuanBieming
     *
     * @return the value of t_jcpeizhi.sjlaiyuanBieming
     *
     * @mbggenerated
     */
    public String getSjlaiyuanBieming() {
        return sjlaiyuanBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.sjlaiyuanBieming
     *
     * @param sjlaiyuanBieming the value for t_jcpeizhi.sjlaiyuanBieming
     *
     * @mbggenerated
     */
    public void setSjlaiyuanBieming(String sjlaiyuanBieming) {
        this.sjlaiyuanBieming = sjlaiyuanBieming == null ? null : sjlaiyuanBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.sjleixingBieming
     *
     * @return the value of t_jcpeizhi.sjleixingBieming
     *
     * @mbggenerated
     */
    public String getSjleixingBieming() {
        return sjleixingBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.sjleixingBieming
     *
     * @param sjleixingBieming the value for t_jcpeizhi.sjleixingBieming
     *
     * @mbggenerated
     */
    public void setSjleixingBieming(String sjleixingBieming) {
        this.sjleixingBieming = sjleixingBieming == null ? null : sjleixingBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.sjpinglunBieming
     *
     * @return the value of t_jcpeizhi.sjpinglunBieming
     *
     * @mbggenerated
     */
    public String getSjpinglunBieming() {
        return sjpinglunBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.sjpinglunBieming
     *
     * @param sjpinglunBieming the value for t_jcpeizhi.sjpinglunBieming
     *
     * @mbggenerated
     */
    public void setSjpinglunBieming(String sjpinglunBieming) {
        this.sjpinglunBieming = sjpinglunBieming == null ? null : sjpinglunBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.sjqitaBieming
     *
     * @return the value of t_jcpeizhi.sjqitaBieming
     *
     * @mbggenerated
     */
    public String getSjqitaBieming() {
        return sjqitaBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.sjqitaBieming
     *
     * @param sjqitaBieming the value for t_jcpeizhi.sjqitaBieming
     *
     * @mbggenerated
     */
    public void setSjqitaBieming(String sjqitaBieming) {
        this.sjqitaBieming = sjqitaBieming == null ? null : sjqitaBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.sjshaochuBieming
     *
     * @return the value of t_jcpeizhi.sjshaochuBieming
     *
     * @mbggenerated
     */
    public String getSjshaochuBieming() {
        return sjshaochuBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.sjshaochuBieming
     *
     * @param sjshaochuBieming the value for t_jcpeizhi.sjshaochuBieming
     *
     * @mbggenerated
     */
    public void setSjshaochuBieming(String sjshaochuBieming) {
        this.sjshaochuBieming = sjshaochuBieming == null ? null : sjshaochuBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.sjxingtaiBieming
     *
     * @return the value of t_jcpeizhi.sjxingtaiBieming
     *
     * @mbggenerated
     */
    public String getSjxingtaiBieming() {
        return sjxingtaiBieming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.sjxingtaiBieming
     *
     * @param sjxingtaiBieming the value for t_jcpeizhi.sjxingtaiBieming
     *
     * @mbggenerated
     */
    public void setSjxingtaiBieming(String sjxingtaiBieming) {
        this.sjxingtaiBieming = sjxingtaiBieming == null ? null : sjxingtaiBieming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.jcpeizhiType
     *
     * @return the value of t_jcpeizhi.jcpeizhiType
     *
     * @mbggenerated
     */
    public Integer getJcpeizhiType() {
        return jcpeizhiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.jcpeizhiType
     *
     * @param jcpeizhiType the value for t_jcpeizhi.jcpeizhiType
     *
     * @mbggenerated
     */
    public void setJcpeizhiType(Integer jcpeizhiType) {
        this.jcpeizhiType = jcpeizhiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.jcpeizhiType1
     *
     * @return the value of t_jcpeizhi.jcpeizhiType1
     *
     * @mbggenerated
     */
    public Integer getJcpeizhiType1() {
        return jcpeizhiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.jcpeizhiType1
     *
     * @param jcpeizhiType1 the value for t_jcpeizhi.jcpeizhiType1
     *
     * @mbggenerated
     */
    public void setJcpeizhiType1(Integer jcpeizhiType1) {
        this.jcpeizhiType1 = jcpeizhiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jcpeizhi.jcpeizhiType2
     *
     * @return the value of t_jcpeizhi.jcpeizhiType2
     *
     * @mbggenerated
     */
    public Integer getJcpeizhiType2() {
        return jcpeizhiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jcpeizhi.jcpeizhiType2
     *
     * @param jcpeizhiType2 the value for t_jcpeizhi.jcpeizhiType2
     *
     * @mbggenerated
     */
    public void setJcpeizhiType2(Integer jcpeizhiType2) {
        this.jcpeizhiType2 = jcpeizhiType2;
    }
}