package com.model;

import java.util.Date;

public class Sjduochu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuId
     *
     * @mbggenerated
     */
    private Integer sjduochuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuName
     *
     * @mbggenerated
     */
    private String sjduochuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuMark
     *
     * @mbggenerated
     */
    private String sjduochuMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuMark1
     *
     * @mbggenerated
     */
    private String sjduochuMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuMark2
     *
     * @mbggenerated
     */
    private String sjduochuMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuMark3
     *
     * @mbggenerated
     */
    private String sjduochuMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDate
     *
     * @mbggenerated
     */
    private Date sjduochuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDate1
     *
     * @mbggenerated
     */
    private Date sjduochuDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuZong
     *
     * @mbggenerated
     */
    private Integer sjduochuZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuZong1
     *
     * @mbggenerated
     */
    private Integer sjduochuZong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuZong2
     *
     * @mbggenerated
     */
    private Integer sjduochuZong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDouble
     *
     * @mbggenerated
     */
    private Double sjduochuDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDouble1
     *
     * @mbggenerated
     */
    private Double sjduochuDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuDouble2
     *
     * @mbggenerated
     */
    private Double sjduochuDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuType
     *
     * @mbggenerated
     */
    private Integer sjduochuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuType1
     *
     * @mbggenerated
     */
    private Integer sjduochuType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuType2
     *
     * @mbggenerated
     */
    private Integer sjduochuType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjqitaId
     *
     * @mbggenerated
     */
    private Integer sjqitaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjqitaName
     *
     * @mbggenerated
     */
    private String sjqitaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjlaiyuanId
     *
     * @mbggenerated
     */
    private Integer sjlaiyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjlaiyuanName
     *
     * @mbggenerated
     */
    private String sjlaiyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuImg
     *
     * @mbggenerated
     */
    private String sjduochuImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjduochuImgName
     *
     * @mbggenerated
     */
    private String sjduochuImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.shujuId
     *
     * @mbggenerated
     */
    private Integer shujuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.shujuName
     *
     * @mbggenerated
     */
    private String shujuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjleixingId
     *
     * @mbggenerated
     */
    private Integer sjleixingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjleixingName
     *
     * @mbggenerated
     */
    private String sjleixingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjxingtaiId
     *
     * @mbggenerated
     */
    private Integer sjxingtaiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.sjxingtaiName
     *
     * @mbggenerated
     */
    private String sjxingtaiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byumenId
     *
     * @mbggenerated
     */
    private Integer byumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byumenName
     *
     * @mbggenerated
     */
    private String byumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byuyuanId
     *
     * @mbggenerated
     */
    private Integer byuyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byuyuanName
     *
     * @mbggenerated
     */
    private String byuyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byuzhiId
     *
     * @mbggenerated
     */
    private Integer byuzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.byuzhiName
     *
     * @mbggenerated
     */
    private String byuzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjduochu.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuId
     *
     * @return the value of t_sjduochu.sjduochuId
     *
     * @mbggenerated
     */
    public Integer getSjduochuId() {
        return sjduochuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuId
     *
     * @param sjduochuId the value for t_sjduochu.sjduochuId
     *
     * @mbggenerated
     */
    public void setSjduochuId(Integer sjduochuId) {
        this.sjduochuId = sjduochuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuName
     *
     * @return the value of t_sjduochu.sjduochuName
     *
     * @mbggenerated
     */
    public String getSjduochuName() {
        return sjduochuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuName
     *
     * @param sjduochuName the value for t_sjduochu.sjduochuName
     *
     * @mbggenerated
     */
    public void setSjduochuName(String sjduochuName) {
        this.sjduochuName = sjduochuName == null ? null : sjduochuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuMark
     *
     * @return the value of t_sjduochu.sjduochuMark
     *
     * @mbggenerated
     */
    public String getSjduochuMark() {
        return sjduochuMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuMark
     *
     * @param sjduochuMark the value for t_sjduochu.sjduochuMark
     *
     * @mbggenerated
     */
    public void setSjduochuMark(String sjduochuMark) {
        this.sjduochuMark = sjduochuMark == null ? null : sjduochuMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuMark1
     *
     * @return the value of t_sjduochu.sjduochuMark1
     *
     * @mbggenerated
     */
    public String getSjduochuMark1() {
        return sjduochuMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuMark1
     *
     * @param sjduochuMark1 the value for t_sjduochu.sjduochuMark1
     *
     * @mbggenerated
     */
    public void setSjduochuMark1(String sjduochuMark1) {
        this.sjduochuMark1 = sjduochuMark1 == null ? null : sjduochuMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuMark2
     *
     * @return the value of t_sjduochu.sjduochuMark2
     *
     * @mbggenerated
     */
    public String getSjduochuMark2() {
        return sjduochuMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuMark2
     *
     * @param sjduochuMark2 the value for t_sjduochu.sjduochuMark2
     *
     * @mbggenerated
     */
    public void setSjduochuMark2(String sjduochuMark2) {
        this.sjduochuMark2 = sjduochuMark2 == null ? null : sjduochuMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuMark3
     *
     * @return the value of t_sjduochu.sjduochuMark3
     *
     * @mbggenerated
     */
    public String getSjduochuMark3() {
        return sjduochuMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuMark3
     *
     * @param sjduochuMark3 the value for t_sjduochu.sjduochuMark3
     *
     * @mbggenerated
     */
    public void setSjduochuMark3(String sjduochuMark3) {
        this.sjduochuMark3 = sjduochuMark3 == null ? null : sjduochuMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDate
     *
     * @return the value of t_sjduochu.sjduochuDate
     *
     * @mbggenerated
     */
    public Date getSjduochuDate() {
        return sjduochuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDate
     *
     * @param sjduochuDate the value for t_sjduochu.sjduochuDate
     *
     * @mbggenerated
     */
    public void setSjduochuDate(Date sjduochuDate) {
        this.sjduochuDate = sjduochuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDate1
     *
     * @return the value of t_sjduochu.sjduochuDate1
     *
     * @mbggenerated
     */
    public Date getSjduochuDate1() {
        return sjduochuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDate1
     *
     * @param sjduochuDate1 the value for t_sjduochu.sjduochuDate1
     *
     * @mbggenerated
     */
    public void setSjduochuDate1(Date sjduochuDate1) {
        this.sjduochuDate1 = sjduochuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuZong
     *
     * @return the value of t_sjduochu.sjduochuZong
     *
     * @mbggenerated
     */
    public Integer getSjduochuZong() {
        return sjduochuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuZong
     *
     * @param sjduochuZong the value for t_sjduochu.sjduochuZong
     *
     * @mbggenerated
     */
    public void setSjduochuZong(Integer sjduochuZong) {
        this.sjduochuZong = sjduochuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuZong1
     *
     * @return the value of t_sjduochu.sjduochuZong1
     *
     * @mbggenerated
     */
    public Integer getSjduochuZong1() {
        return sjduochuZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuZong1
     *
     * @param sjduochuZong1 the value for t_sjduochu.sjduochuZong1
     *
     * @mbggenerated
     */
    public void setSjduochuZong1(Integer sjduochuZong1) {
        this.sjduochuZong1 = sjduochuZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuZong2
     *
     * @return the value of t_sjduochu.sjduochuZong2
     *
     * @mbggenerated
     */
    public Integer getSjduochuZong2() {
        return sjduochuZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuZong2
     *
     * @param sjduochuZong2 the value for t_sjduochu.sjduochuZong2
     *
     * @mbggenerated
     */
    public void setSjduochuZong2(Integer sjduochuZong2) {
        this.sjduochuZong2 = sjduochuZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDouble
     *
     * @return the value of t_sjduochu.sjduochuDouble
     *
     * @mbggenerated
     */
    public Double getSjduochuDouble() {
        return sjduochuDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDouble
     *
     * @param sjduochuDouble the value for t_sjduochu.sjduochuDouble
     *
     * @mbggenerated
     */
    public void setSjduochuDouble(Double sjduochuDouble) {
        this.sjduochuDouble = sjduochuDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDouble1
     *
     * @return the value of t_sjduochu.sjduochuDouble1
     *
     * @mbggenerated
     */
    public Double getSjduochuDouble1() {
        return sjduochuDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDouble1
     *
     * @param sjduochuDouble1 the value for t_sjduochu.sjduochuDouble1
     *
     * @mbggenerated
     */
    public void setSjduochuDouble1(Double sjduochuDouble1) {
        this.sjduochuDouble1 = sjduochuDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuDouble2
     *
     * @return the value of t_sjduochu.sjduochuDouble2
     *
     * @mbggenerated
     */
    public Double getSjduochuDouble2() {
        return sjduochuDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuDouble2
     *
     * @param sjduochuDouble2 the value for t_sjduochu.sjduochuDouble2
     *
     * @mbggenerated
     */
    public void setSjduochuDouble2(Double sjduochuDouble2) {
        this.sjduochuDouble2 = sjduochuDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuType
     *
     * @return the value of t_sjduochu.sjduochuType
     *
     * @mbggenerated
     */
    public Integer getSjduochuType() {
        return sjduochuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuType
     *
     * @param sjduochuType the value for t_sjduochu.sjduochuType
     *
     * @mbggenerated
     */
    public void setSjduochuType(Integer sjduochuType) {
        this.sjduochuType = sjduochuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuType1
     *
     * @return the value of t_sjduochu.sjduochuType1
     *
     * @mbggenerated
     */
    public Integer getSjduochuType1() {
        return sjduochuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuType1
     *
     * @param sjduochuType1 the value for t_sjduochu.sjduochuType1
     *
     * @mbggenerated
     */
    public void setSjduochuType1(Integer sjduochuType1) {
        this.sjduochuType1 = sjduochuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuType2
     *
     * @return the value of t_sjduochu.sjduochuType2
     *
     * @mbggenerated
     */
    public Integer getSjduochuType2() {
        return sjduochuType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuType2
     *
     * @param sjduochuType2 the value for t_sjduochu.sjduochuType2
     *
     * @mbggenerated
     */
    public void setSjduochuType2(Integer sjduochuType2) {
        this.sjduochuType2 = sjduochuType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjqitaId
     *
     * @return the value of t_sjduochu.sjqitaId
     *
     * @mbggenerated
     */
    public Integer getSjqitaId() {
        return sjqitaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjqitaId
     *
     * @param sjqitaId the value for t_sjduochu.sjqitaId
     *
     * @mbggenerated
     */
    public void setSjqitaId(Integer sjqitaId) {
        this.sjqitaId = sjqitaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjqitaName
     *
     * @return the value of t_sjduochu.sjqitaName
     *
     * @mbggenerated
     */
    public String getSjqitaName() {
        return sjqitaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjqitaName
     *
     * @param sjqitaName the value for t_sjduochu.sjqitaName
     *
     * @mbggenerated
     */
    public void setSjqitaName(String sjqitaName) {
        this.sjqitaName = sjqitaName == null ? null : sjqitaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjlaiyuanId
     *
     * @return the value of t_sjduochu.sjlaiyuanId
     *
     * @mbggenerated
     */
    public Integer getSjlaiyuanId() {
        return sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjlaiyuanId
     *
     * @param sjlaiyuanId the value for t_sjduochu.sjlaiyuanId
     *
     * @mbggenerated
     */
    public void setSjlaiyuanId(Integer sjlaiyuanId) {
        this.sjlaiyuanId = sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjlaiyuanName
     *
     * @return the value of t_sjduochu.sjlaiyuanName
     *
     * @mbggenerated
     */
    public String getSjlaiyuanName() {
        return sjlaiyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjlaiyuanName
     *
     * @param sjlaiyuanName the value for t_sjduochu.sjlaiyuanName
     *
     * @mbggenerated
     */
    public void setSjlaiyuanName(String sjlaiyuanName) {
        this.sjlaiyuanName = sjlaiyuanName == null ? null : sjlaiyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuImg
     *
     * @return the value of t_sjduochu.sjduochuImg
     *
     * @mbggenerated
     */
    public String getSjduochuImg() {
        return sjduochuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuImg
     *
     * @param sjduochuImg the value for t_sjduochu.sjduochuImg
     *
     * @mbggenerated
     */
    public void setSjduochuImg(String sjduochuImg) {
        this.sjduochuImg = sjduochuImg == null ? null : sjduochuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjduochuImgName
     *
     * @return the value of t_sjduochu.sjduochuImgName
     *
     * @mbggenerated
     */
    public String getSjduochuImgName() {
        return sjduochuImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjduochuImgName
     *
     * @param sjduochuImgName the value for t_sjduochu.sjduochuImgName
     *
     * @mbggenerated
     */
    public void setSjduochuImgName(String sjduochuImgName) {
        this.sjduochuImgName = sjduochuImgName == null ? null : sjduochuImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.shujuId
     *
     * @return the value of t_sjduochu.shujuId
     *
     * @mbggenerated
     */
    public Integer getShujuId() {
        return shujuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.shujuId
     *
     * @param shujuId the value for t_sjduochu.shujuId
     *
     * @mbggenerated
     */
    public void setShujuId(Integer shujuId) {
        this.shujuId = shujuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.shujuName
     *
     * @return the value of t_sjduochu.shujuName
     *
     * @mbggenerated
     */
    public String getShujuName() {
        return shujuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.shujuName
     *
     * @param shujuName the value for t_sjduochu.shujuName
     *
     * @mbggenerated
     */
    public void setShujuName(String shujuName) {
        this.shujuName = shujuName == null ? null : shujuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjleixingId
     *
     * @return the value of t_sjduochu.sjleixingId
     *
     * @mbggenerated
     */
    public Integer getSjleixingId() {
        return sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjleixingId
     *
     * @param sjleixingId the value for t_sjduochu.sjleixingId
     *
     * @mbggenerated
     */
    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjleixingName
     *
     * @return the value of t_sjduochu.sjleixingName
     *
     * @mbggenerated
     */
    public String getSjleixingName() {
        return sjleixingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjleixingName
     *
     * @param sjleixingName the value for t_sjduochu.sjleixingName
     *
     * @mbggenerated
     */
    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjxingtaiId
     *
     * @return the value of t_sjduochu.sjxingtaiId
     *
     * @mbggenerated
     */
    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjxingtaiId
     *
     * @param sjxingtaiId the value for t_sjduochu.sjxingtaiId
     *
     * @mbggenerated
     */
    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.sjxingtaiName
     *
     * @return the value of t_sjduochu.sjxingtaiName
     *
     * @mbggenerated
     */
    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.sjxingtaiName
     *
     * @param sjxingtaiName the value for t_sjduochu.sjxingtaiName
     *
     * @mbggenerated
     */
    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.userId
     *
     * @return the value of t_sjduochu.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.userId
     *
     * @param userId the value for t_sjduochu.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.userName
     *
     * @return the value of t_sjduochu.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.userName
     *
     * @param userName the value for t_sjduochu.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.bumenId
     *
     * @return the value of t_sjduochu.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.bumenId
     *
     * @param bumenId the value for t_sjduochu.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.bumenName
     *
     * @return the value of t_sjduochu.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.bumenName
     *
     * @param bumenName the value for t_sjduochu.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.buyuanId
     *
     * @return the value of t_sjduochu.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.buyuanId
     *
     * @param buyuanId the value for t_sjduochu.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.buyuanName
     *
     * @return the value of t_sjduochu.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.buyuanName
     *
     * @param buyuanName the value for t_sjduochu.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.yonghuId
     *
     * @return the value of t_sjduochu.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.yonghuId
     *
     * @param yonghuId the value for t_sjduochu.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.yonghuName
     *
     * @return the value of t_sjduochu.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.yonghuName
     *
     * @param yonghuName the value for t_sjduochu.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byumenId
     *
     * @return the value of t_sjduochu.byumenId
     *
     * @mbggenerated
     */
    public Integer getByumenId() {
        return byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byumenId
     *
     * @param byumenId the value for t_sjduochu.byumenId
     *
     * @mbggenerated
     */
    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byumenName
     *
     * @return the value of t_sjduochu.byumenName
     *
     * @mbggenerated
     */
    public String getByumenName() {
        return byumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byumenName
     *
     * @param byumenName the value for t_sjduochu.byumenName
     *
     * @mbggenerated
     */
    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byuyuanId
     *
     * @return the value of t_sjduochu.byuyuanId
     *
     * @mbggenerated
     */
    public Integer getByuyuanId() {
        return byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byuyuanId
     *
     * @param byuyuanId the value for t_sjduochu.byuyuanId
     *
     * @mbggenerated
     */
    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byuyuanName
     *
     * @return the value of t_sjduochu.byuyuanName
     *
     * @mbggenerated
     */
    public String getByuyuanName() {
        return byuyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byuyuanName
     *
     * @param byuyuanName the value for t_sjduochu.byuyuanName
     *
     * @mbggenerated
     */
    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.buzhiId
     *
     * @return the value of t_sjduochu.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.buzhiId
     *
     * @param buzhiId the value for t_sjduochu.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.buzhiName
     *
     * @return the value of t_sjduochu.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.buzhiName
     *
     * @param buzhiName the value for t_sjduochu.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.roleId
     *
     * @return the value of t_sjduochu.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.roleId
     *
     * @param roleId the value for t_sjduochu.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.roleName
     *
     * @return the value of t_sjduochu.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.roleName
     *
     * @param roleName the value for t_sjduochu.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byuzhiId
     *
     * @return the value of t_sjduochu.byuzhiId
     *
     * @mbggenerated
     */
    public Integer getByuzhiId() {
        return byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byuzhiId
     *
     * @param byuzhiId the value for t_sjduochu.byuzhiId
     *
     * @mbggenerated
     */
    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.byuzhiName
     *
     * @return the value of t_sjduochu.byuzhiName
     *
     * @mbggenerated
     */
    public String getByuzhiName() {
        return byuzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.byuzhiName
     *
     * @param byuzhiName the value for t_sjduochu.byuzhiName
     *
     * @mbggenerated
     */
    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.yhroleId
     *
     * @return the value of t_sjduochu.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.yhroleId
     *
     * @param yhroleId the value for t_sjduochu.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjduochu.yhroleName
     *
     * @return the value of t_sjduochu.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjduochu.yhroleName
     *
     * @param yhroleName the value for t_sjduochu.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}