package com.model;

import java.util.Date;

public class Sjjianchu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuId
     *
     * @mbggenerated
     */
    private Integer sjjianchuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuName
     *
     * @mbggenerated
     */
    private String sjjianchuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuMark
     *
     * @mbggenerated
     */
    private String sjjianchuMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuMark1
     *
     * @mbggenerated
     */
    private String sjjianchuMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuMark2
     *
     * @mbggenerated
     */
    private String sjjianchuMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuMark3
     *
     * @mbggenerated
     */
    private String sjjianchuMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDate
     *
     * @mbggenerated
     */
    private Date sjjianchuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDate1
     *
     * @mbggenerated
     */
    private Date sjjianchuDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuZong
     *
     * @mbggenerated
     */
    private Integer sjjianchuZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuZong1
     *
     * @mbggenerated
     */
    private Integer sjjianchuZong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuZong2
     *
     * @mbggenerated
     */
    private Integer sjjianchuZong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDouble
     *
     * @mbggenerated
     */
    private Double sjjianchuDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDouble1
     *
     * @mbggenerated
     */
    private Double sjjianchuDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuDouble2
     *
     * @mbggenerated
     */
    private Double sjjianchuDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuType
     *
     * @mbggenerated
     */
    private Integer sjjianchuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuType1
     *
     * @mbggenerated
     */
    private Integer sjjianchuType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuType2
     *
     * @mbggenerated
     */
    private Integer sjjianchuType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjqitaId
     *
     * @mbggenerated
     */
    private Integer sjqitaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjqitaName
     *
     * @mbggenerated
     */
    private String sjqitaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjlaiyuanId
     *
     * @mbggenerated
     */
    private Integer sjlaiyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjlaiyuanName
     *
     * @mbggenerated
     */
    private String sjlaiyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuImg
     *
     * @mbggenerated
     */
    private String sjjianchuImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjjianchuImgName
     *
     * @mbggenerated
     */
    private String sjjianchuImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.shujuId
     *
     * @mbggenerated
     */
    private Integer shujuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.shujuName
     *
     * @mbggenerated
     */
    private String shujuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjleixingId
     *
     * @mbggenerated
     */
    private Integer sjleixingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjleixingName
     *
     * @mbggenerated
     */
    private String sjleixingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjxingtaiId
     *
     * @mbggenerated
     */
    private Integer sjxingtaiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.sjxingtaiName
     *
     * @mbggenerated
     */
    private String sjxingtaiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byumenId
     *
     * @mbggenerated
     */
    private Integer byumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byumenName
     *
     * @mbggenerated
     */
    private String byumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byuyuanId
     *
     * @mbggenerated
     */
    private Integer byuyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byuyuanName
     *
     * @mbggenerated
     */
    private String byuyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byuzhiId
     *
     * @mbggenerated
     */
    private Integer byuzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.byuzhiName
     *
     * @mbggenerated
     */
    private String byuzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjjianchu.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuId
     *
     * @return the value of t_sjjianchu.sjjianchuId
     *
     * @mbggenerated
     */
    public Integer getSjjianchuId() {
        return sjjianchuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuId
     *
     * @param sjjianchuId the value for t_sjjianchu.sjjianchuId
     *
     * @mbggenerated
     */
    public void setSjjianchuId(Integer sjjianchuId) {
        this.sjjianchuId = sjjianchuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuName
     *
     * @return the value of t_sjjianchu.sjjianchuName
     *
     * @mbggenerated
     */
    public String getSjjianchuName() {
        return sjjianchuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuName
     *
     * @param sjjianchuName the value for t_sjjianchu.sjjianchuName
     *
     * @mbggenerated
     */
    public void setSjjianchuName(String sjjianchuName) {
        this.sjjianchuName = sjjianchuName == null ? null : sjjianchuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuMark
     *
     * @return the value of t_sjjianchu.sjjianchuMark
     *
     * @mbggenerated
     */
    public String getSjjianchuMark() {
        return sjjianchuMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuMark
     *
     * @param sjjianchuMark the value for t_sjjianchu.sjjianchuMark
     *
     * @mbggenerated
     */
    public void setSjjianchuMark(String sjjianchuMark) {
        this.sjjianchuMark = sjjianchuMark == null ? null : sjjianchuMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuMark1
     *
     * @return the value of t_sjjianchu.sjjianchuMark1
     *
     * @mbggenerated
     */
    public String getSjjianchuMark1() {
        return sjjianchuMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuMark1
     *
     * @param sjjianchuMark1 the value for t_sjjianchu.sjjianchuMark1
     *
     * @mbggenerated
     */
    public void setSjjianchuMark1(String sjjianchuMark1) {
        this.sjjianchuMark1 = sjjianchuMark1 == null ? null : sjjianchuMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuMark2
     *
     * @return the value of t_sjjianchu.sjjianchuMark2
     *
     * @mbggenerated
     */
    public String getSjjianchuMark2() {
        return sjjianchuMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuMark2
     *
     * @param sjjianchuMark2 the value for t_sjjianchu.sjjianchuMark2
     *
     * @mbggenerated
     */
    public void setSjjianchuMark2(String sjjianchuMark2) {
        this.sjjianchuMark2 = sjjianchuMark2 == null ? null : sjjianchuMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuMark3
     *
     * @return the value of t_sjjianchu.sjjianchuMark3
     *
     * @mbggenerated
     */
    public String getSjjianchuMark3() {
        return sjjianchuMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuMark3
     *
     * @param sjjianchuMark3 the value for t_sjjianchu.sjjianchuMark3
     *
     * @mbggenerated
     */
    public void setSjjianchuMark3(String sjjianchuMark3) {
        this.sjjianchuMark3 = sjjianchuMark3 == null ? null : sjjianchuMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDate
     *
     * @return the value of t_sjjianchu.sjjianchuDate
     *
     * @mbggenerated
     */
    public Date getSjjianchuDate() {
        return sjjianchuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDate
     *
     * @param sjjianchuDate the value for t_sjjianchu.sjjianchuDate
     *
     * @mbggenerated
     */
    public void setSjjianchuDate(Date sjjianchuDate) {
        this.sjjianchuDate = sjjianchuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDate1
     *
     * @return the value of t_sjjianchu.sjjianchuDate1
     *
     * @mbggenerated
     */
    public Date getSjjianchuDate1() {
        return sjjianchuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDate1
     *
     * @param sjjianchuDate1 the value for t_sjjianchu.sjjianchuDate1
     *
     * @mbggenerated
     */
    public void setSjjianchuDate1(Date sjjianchuDate1) {
        this.sjjianchuDate1 = sjjianchuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuZong
     *
     * @return the value of t_sjjianchu.sjjianchuZong
     *
     * @mbggenerated
     */
    public Integer getSjjianchuZong() {
        return sjjianchuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuZong
     *
     * @param sjjianchuZong the value for t_sjjianchu.sjjianchuZong
     *
     * @mbggenerated
     */
    public void setSjjianchuZong(Integer sjjianchuZong) {
        this.sjjianchuZong = sjjianchuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuZong1
     *
     * @return the value of t_sjjianchu.sjjianchuZong1
     *
     * @mbggenerated
     */
    public Integer getSjjianchuZong1() {
        return sjjianchuZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuZong1
     *
     * @param sjjianchuZong1 the value for t_sjjianchu.sjjianchuZong1
     *
     * @mbggenerated
     */
    public void setSjjianchuZong1(Integer sjjianchuZong1) {
        this.sjjianchuZong1 = sjjianchuZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuZong2
     *
     * @return the value of t_sjjianchu.sjjianchuZong2
     *
     * @mbggenerated
     */
    public Integer getSjjianchuZong2() {
        return sjjianchuZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuZong2
     *
     * @param sjjianchuZong2 the value for t_sjjianchu.sjjianchuZong2
     *
     * @mbggenerated
     */
    public void setSjjianchuZong2(Integer sjjianchuZong2) {
        this.sjjianchuZong2 = sjjianchuZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDouble
     *
     * @return the value of t_sjjianchu.sjjianchuDouble
     *
     * @mbggenerated
     */
    public Double getSjjianchuDouble() {
        return sjjianchuDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDouble
     *
     * @param sjjianchuDouble the value for t_sjjianchu.sjjianchuDouble
     *
     * @mbggenerated
     */
    public void setSjjianchuDouble(Double sjjianchuDouble) {
        this.sjjianchuDouble = sjjianchuDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDouble1
     *
     * @return the value of t_sjjianchu.sjjianchuDouble1
     *
     * @mbggenerated
     */
    public Double getSjjianchuDouble1() {
        return sjjianchuDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDouble1
     *
     * @param sjjianchuDouble1 the value for t_sjjianchu.sjjianchuDouble1
     *
     * @mbggenerated
     */
    public void setSjjianchuDouble1(Double sjjianchuDouble1) {
        this.sjjianchuDouble1 = sjjianchuDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuDouble2
     *
     * @return the value of t_sjjianchu.sjjianchuDouble2
     *
     * @mbggenerated
     */
    public Double getSjjianchuDouble2() {
        return sjjianchuDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuDouble2
     *
     * @param sjjianchuDouble2 the value for t_sjjianchu.sjjianchuDouble2
     *
     * @mbggenerated
     */
    public void setSjjianchuDouble2(Double sjjianchuDouble2) {
        this.sjjianchuDouble2 = sjjianchuDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuType
     *
     * @return the value of t_sjjianchu.sjjianchuType
     *
     * @mbggenerated
     */
    public Integer getSjjianchuType() {
        return sjjianchuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuType
     *
     * @param sjjianchuType the value for t_sjjianchu.sjjianchuType
     *
     * @mbggenerated
     */
    public void setSjjianchuType(Integer sjjianchuType) {
        this.sjjianchuType = sjjianchuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuType1
     *
     * @return the value of t_sjjianchu.sjjianchuType1
     *
     * @mbggenerated
     */
    public Integer getSjjianchuType1() {
        return sjjianchuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuType1
     *
     * @param sjjianchuType1 the value for t_sjjianchu.sjjianchuType1
     *
     * @mbggenerated
     */
    public void setSjjianchuType1(Integer sjjianchuType1) {
        this.sjjianchuType1 = sjjianchuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuType2
     *
     * @return the value of t_sjjianchu.sjjianchuType2
     *
     * @mbggenerated
     */
    public Integer getSjjianchuType2() {
        return sjjianchuType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuType2
     *
     * @param sjjianchuType2 the value for t_sjjianchu.sjjianchuType2
     *
     * @mbggenerated
     */
    public void setSjjianchuType2(Integer sjjianchuType2) {
        this.sjjianchuType2 = sjjianchuType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjqitaId
     *
     * @return the value of t_sjjianchu.sjqitaId
     *
     * @mbggenerated
     */
    public Integer getSjqitaId() {
        return sjqitaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjqitaId
     *
     * @param sjqitaId the value for t_sjjianchu.sjqitaId
     *
     * @mbggenerated
     */
    public void setSjqitaId(Integer sjqitaId) {
        this.sjqitaId = sjqitaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjqitaName
     *
     * @return the value of t_sjjianchu.sjqitaName
     *
     * @mbggenerated
     */
    public String getSjqitaName() {
        return sjqitaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjqitaName
     *
     * @param sjqitaName the value for t_sjjianchu.sjqitaName
     *
     * @mbggenerated
     */
    public void setSjqitaName(String sjqitaName) {
        this.sjqitaName = sjqitaName == null ? null : sjqitaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjlaiyuanId
     *
     * @return the value of t_sjjianchu.sjlaiyuanId
     *
     * @mbggenerated
     */
    public Integer getSjlaiyuanId() {
        return sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjlaiyuanId
     *
     * @param sjlaiyuanId the value for t_sjjianchu.sjlaiyuanId
     *
     * @mbggenerated
     */
    public void setSjlaiyuanId(Integer sjlaiyuanId) {
        this.sjlaiyuanId = sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjlaiyuanName
     *
     * @return the value of t_sjjianchu.sjlaiyuanName
     *
     * @mbggenerated
     */
    public String getSjlaiyuanName() {
        return sjlaiyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjlaiyuanName
     *
     * @param sjlaiyuanName the value for t_sjjianchu.sjlaiyuanName
     *
     * @mbggenerated
     */
    public void setSjlaiyuanName(String sjlaiyuanName) {
        this.sjlaiyuanName = sjlaiyuanName == null ? null : sjlaiyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuImg
     *
     * @return the value of t_sjjianchu.sjjianchuImg
     *
     * @mbggenerated
     */
    public String getSjjianchuImg() {
        return sjjianchuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuImg
     *
     * @param sjjianchuImg the value for t_sjjianchu.sjjianchuImg
     *
     * @mbggenerated
     */
    public void setSjjianchuImg(String sjjianchuImg) {
        this.sjjianchuImg = sjjianchuImg == null ? null : sjjianchuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjjianchuImgName
     *
     * @return the value of t_sjjianchu.sjjianchuImgName
     *
     * @mbggenerated
     */
    public String getSjjianchuImgName() {
        return sjjianchuImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjjianchuImgName
     *
     * @param sjjianchuImgName the value for t_sjjianchu.sjjianchuImgName
     *
     * @mbggenerated
     */
    public void setSjjianchuImgName(String sjjianchuImgName) {
        this.sjjianchuImgName = sjjianchuImgName == null ? null : sjjianchuImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.shujuId
     *
     * @return the value of t_sjjianchu.shujuId
     *
     * @mbggenerated
     */
    public Integer getShujuId() {
        return shujuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.shujuId
     *
     * @param shujuId the value for t_sjjianchu.shujuId
     *
     * @mbggenerated
     */
    public void setShujuId(Integer shujuId) {
        this.shujuId = shujuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.shujuName
     *
     * @return the value of t_sjjianchu.shujuName
     *
     * @mbggenerated
     */
    public String getShujuName() {
        return shujuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.shujuName
     *
     * @param shujuName the value for t_sjjianchu.shujuName
     *
     * @mbggenerated
     */
    public void setShujuName(String shujuName) {
        this.shujuName = shujuName == null ? null : shujuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjleixingId
     *
     * @return the value of t_sjjianchu.sjleixingId
     *
     * @mbggenerated
     */
    public Integer getSjleixingId() {
        return sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjleixingId
     *
     * @param sjleixingId the value for t_sjjianchu.sjleixingId
     *
     * @mbggenerated
     */
    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjleixingName
     *
     * @return the value of t_sjjianchu.sjleixingName
     *
     * @mbggenerated
     */
    public String getSjleixingName() {
        return sjleixingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjleixingName
     *
     * @param sjleixingName the value for t_sjjianchu.sjleixingName
     *
     * @mbggenerated
     */
    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjxingtaiId
     *
     * @return the value of t_sjjianchu.sjxingtaiId
     *
     * @mbggenerated
     */
    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjxingtaiId
     *
     * @param sjxingtaiId the value for t_sjjianchu.sjxingtaiId
     *
     * @mbggenerated
     */
    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.sjxingtaiName
     *
     * @return the value of t_sjjianchu.sjxingtaiName
     *
     * @mbggenerated
     */
    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.sjxingtaiName
     *
     * @param sjxingtaiName the value for t_sjjianchu.sjxingtaiName
     *
     * @mbggenerated
     */
    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.userId
     *
     * @return the value of t_sjjianchu.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.userId
     *
     * @param userId the value for t_sjjianchu.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.userName
     *
     * @return the value of t_sjjianchu.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.userName
     *
     * @param userName the value for t_sjjianchu.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.bumenId
     *
     * @return the value of t_sjjianchu.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.bumenId
     *
     * @param bumenId the value for t_sjjianchu.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.bumenName
     *
     * @return the value of t_sjjianchu.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.bumenName
     *
     * @param bumenName the value for t_sjjianchu.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.buyuanId
     *
     * @return the value of t_sjjianchu.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.buyuanId
     *
     * @param buyuanId the value for t_sjjianchu.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.buyuanName
     *
     * @return the value of t_sjjianchu.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.buyuanName
     *
     * @param buyuanName the value for t_sjjianchu.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.yonghuId
     *
     * @return the value of t_sjjianchu.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.yonghuId
     *
     * @param yonghuId the value for t_sjjianchu.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.yonghuName
     *
     * @return the value of t_sjjianchu.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.yonghuName
     *
     * @param yonghuName the value for t_sjjianchu.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byumenId
     *
     * @return the value of t_sjjianchu.byumenId
     *
     * @mbggenerated
     */
    public Integer getByumenId() {
        return byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byumenId
     *
     * @param byumenId the value for t_sjjianchu.byumenId
     *
     * @mbggenerated
     */
    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byumenName
     *
     * @return the value of t_sjjianchu.byumenName
     *
     * @mbggenerated
     */
    public String getByumenName() {
        return byumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byumenName
     *
     * @param byumenName the value for t_sjjianchu.byumenName
     *
     * @mbggenerated
     */
    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byuyuanId
     *
     * @return the value of t_sjjianchu.byuyuanId
     *
     * @mbggenerated
     */
    public Integer getByuyuanId() {
        return byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byuyuanId
     *
     * @param byuyuanId the value for t_sjjianchu.byuyuanId
     *
     * @mbggenerated
     */
    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byuyuanName
     *
     * @return the value of t_sjjianchu.byuyuanName
     *
     * @mbggenerated
     */
    public String getByuyuanName() {
        return byuyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byuyuanName
     *
     * @param byuyuanName the value for t_sjjianchu.byuyuanName
     *
     * @mbggenerated
     */
    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.buzhiId
     *
     * @return the value of t_sjjianchu.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.buzhiId
     *
     * @param buzhiId the value for t_sjjianchu.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.buzhiName
     *
     * @return the value of t_sjjianchu.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.buzhiName
     *
     * @param buzhiName the value for t_sjjianchu.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.roleId
     *
     * @return the value of t_sjjianchu.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.roleId
     *
     * @param roleId the value for t_sjjianchu.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.roleName
     *
     * @return the value of t_sjjianchu.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.roleName
     *
     * @param roleName the value for t_sjjianchu.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byuzhiId
     *
     * @return the value of t_sjjianchu.byuzhiId
     *
     * @mbggenerated
     */
    public Integer getByuzhiId() {
        return byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byuzhiId
     *
     * @param byuzhiId the value for t_sjjianchu.byuzhiId
     *
     * @mbggenerated
     */
    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.byuzhiName
     *
     * @return the value of t_sjjianchu.byuzhiName
     *
     * @mbggenerated
     */
    public String getByuzhiName() {
        return byuzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.byuzhiName
     *
     * @param byuzhiName the value for t_sjjianchu.byuzhiName
     *
     * @mbggenerated
     */
    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.yhroleId
     *
     * @return the value of t_sjjianchu.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.yhroleId
     *
     * @param yhroleId the value for t_sjjianchu.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjjianchu.yhroleName
     *
     * @return the value of t_sjjianchu.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjjianchu.yhroleName
     *
     * @param yhroleName the value for t_sjjianchu.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}