package com.model;

import java.util.Date;

public class Sjlaiyuan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanId
     *
     * @mbggenerated
     */
    private Integer sjlaiyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanName
     *
     * @mbggenerated
     */
    private String sjlaiyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanMark
     *
     * @mbggenerated
     */
    private String sjlaiyuanMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanMark1
     *
     * @mbggenerated
     */
    private String sjlaiyuanMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanMark2
     *
     * @mbggenerated
     */
    private String sjlaiyuanMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanPhone
     *
     * @mbggenerated
     */
    private String sjlaiyuanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanDizhi
     *
     * @mbggenerated
     */
    private String sjlaiyuanDizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanDate
     *
     * @mbggenerated
     */
    private Date sjlaiyuanDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanDate1
     *
     * @mbggenerated
     */
    private Date sjlaiyuanDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanType
     *
     * @mbggenerated
     */
    private Integer sjlaiyuanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanType1
     *
     * @mbggenerated
     */
    private Integer sjlaiyuanType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanDouble
     *
     * @mbggenerated
     */
    private Double sjlaiyuanDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjlaiyuan.sjlaiyuanDouble1
     *
     * @mbggenerated
     */
    private Double sjlaiyuanDouble1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanId
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanId
     *
     * @mbggenerated
     */
    public Integer getSjlaiyuanId() {
        return sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanId
     *
     * @param sjlaiyuanId the value for t_sjlaiyuan.sjlaiyuanId
     *
     * @mbggenerated
     */
    public void setSjlaiyuanId(Integer sjlaiyuanId) {
        this.sjlaiyuanId = sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanName
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanName
     *
     * @mbggenerated
     */
    public String getSjlaiyuanName() {
        return sjlaiyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanName
     *
     * @param sjlaiyuanName the value for t_sjlaiyuan.sjlaiyuanName
     *
     * @mbggenerated
     */
    public void setSjlaiyuanName(String sjlaiyuanName) {
        this.sjlaiyuanName = sjlaiyuanName == null ? null : sjlaiyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanMark
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanMark
     *
     * @mbggenerated
     */
    public String getSjlaiyuanMark() {
        return sjlaiyuanMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanMark
     *
     * @param sjlaiyuanMark the value for t_sjlaiyuan.sjlaiyuanMark
     *
     * @mbggenerated
     */
    public void setSjlaiyuanMark(String sjlaiyuanMark) {
        this.sjlaiyuanMark = sjlaiyuanMark == null ? null : sjlaiyuanMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanMark1
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanMark1
     *
     * @mbggenerated
     */
    public String getSjlaiyuanMark1() {
        return sjlaiyuanMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanMark1
     *
     * @param sjlaiyuanMark1 the value for t_sjlaiyuan.sjlaiyuanMark1
     *
     * @mbggenerated
     */
    public void setSjlaiyuanMark1(String sjlaiyuanMark1) {
        this.sjlaiyuanMark1 = sjlaiyuanMark1 == null ? null : sjlaiyuanMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanMark2
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanMark2
     *
     * @mbggenerated
     */
    public String getSjlaiyuanMark2() {
        return sjlaiyuanMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanMark2
     *
     * @param sjlaiyuanMark2 the value for t_sjlaiyuan.sjlaiyuanMark2
     *
     * @mbggenerated
     */
    public void setSjlaiyuanMark2(String sjlaiyuanMark2) {
        this.sjlaiyuanMark2 = sjlaiyuanMark2 == null ? null : sjlaiyuanMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanPhone
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanPhone
     *
     * @mbggenerated
     */
    public String getSjlaiyuanPhone() {
        return sjlaiyuanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanPhone
     *
     * @param sjlaiyuanPhone the value for t_sjlaiyuan.sjlaiyuanPhone
     *
     * @mbggenerated
     */
    public void setSjlaiyuanPhone(String sjlaiyuanPhone) {
        this.sjlaiyuanPhone = sjlaiyuanPhone == null ? null : sjlaiyuanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanDizhi
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanDizhi
     *
     * @mbggenerated
     */
    public String getSjlaiyuanDizhi() {
        return sjlaiyuanDizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanDizhi
     *
     * @param sjlaiyuanDizhi the value for t_sjlaiyuan.sjlaiyuanDizhi
     *
     * @mbggenerated
     */
    public void setSjlaiyuanDizhi(String sjlaiyuanDizhi) {
        this.sjlaiyuanDizhi = sjlaiyuanDizhi == null ? null : sjlaiyuanDizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanDate
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanDate
     *
     * @mbggenerated
     */
    public Date getSjlaiyuanDate() {
        return sjlaiyuanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanDate
     *
     * @param sjlaiyuanDate the value for t_sjlaiyuan.sjlaiyuanDate
     *
     * @mbggenerated
     */
    public void setSjlaiyuanDate(Date sjlaiyuanDate) {
        this.sjlaiyuanDate = sjlaiyuanDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanDate1
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanDate1
     *
     * @mbggenerated
     */
    public Date getSjlaiyuanDate1() {
        return sjlaiyuanDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanDate1
     *
     * @param sjlaiyuanDate1 the value for t_sjlaiyuan.sjlaiyuanDate1
     *
     * @mbggenerated
     */
    public void setSjlaiyuanDate1(Date sjlaiyuanDate1) {
        this.sjlaiyuanDate1 = sjlaiyuanDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanType
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanType
     *
     * @mbggenerated
     */
    public Integer getSjlaiyuanType() {
        return sjlaiyuanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanType
     *
     * @param sjlaiyuanType the value for t_sjlaiyuan.sjlaiyuanType
     *
     * @mbggenerated
     */
    public void setSjlaiyuanType(Integer sjlaiyuanType) {
        this.sjlaiyuanType = sjlaiyuanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanType1
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanType1
     *
     * @mbggenerated
     */
    public Integer getSjlaiyuanType1() {
        return sjlaiyuanType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanType1
     *
     * @param sjlaiyuanType1 the value for t_sjlaiyuan.sjlaiyuanType1
     *
     * @mbggenerated
     */
    public void setSjlaiyuanType1(Integer sjlaiyuanType1) {
        this.sjlaiyuanType1 = sjlaiyuanType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanDouble
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanDouble
     *
     * @mbggenerated
     */
    public Double getSjlaiyuanDouble() {
        return sjlaiyuanDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanDouble
     *
     * @param sjlaiyuanDouble the value for t_sjlaiyuan.sjlaiyuanDouble
     *
     * @mbggenerated
     */
    public void setSjlaiyuanDouble(Double sjlaiyuanDouble) {
        this.sjlaiyuanDouble = sjlaiyuanDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjlaiyuan.sjlaiyuanDouble1
     *
     * @return the value of t_sjlaiyuan.sjlaiyuanDouble1
     *
     * @mbggenerated
     */
    public Double getSjlaiyuanDouble1() {
        return sjlaiyuanDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjlaiyuan.sjlaiyuanDouble1
     *
     * @param sjlaiyuanDouble1 the value for t_sjlaiyuan.sjlaiyuanDouble1
     *
     * @mbggenerated
     */
    public void setSjlaiyuanDouble1(Double sjlaiyuanDouble1) {
        this.sjlaiyuanDouble1 = sjlaiyuanDouble1;
    }
}