package com.model;

import java.util.Date;

public class Sjleixing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingId
     *
     * @mbggenerated
     */
    private Integer sjleixingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingName
     *
     * @mbggenerated
     */
    private String sjleixingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingMark
     *
     * @mbggenerated
     */
    private String sjleixingMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingMark1
     *
     * @mbggenerated
     */
    private String sjleixingMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingMark2
     *
     * @mbggenerated
     */
    private String sjleixingMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingPhone
     *
     * @mbggenerated
     */
    private String sjleixingPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDizhi
     *
     * @mbggenerated
     */
    private String sjleixingDizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDate
     *
     * @mbggenerated
     */
    private Date sjleixingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDate1
     *
     * @mbggenerated
     */
    private Date sjleixingDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingType
     *
     * @mbggenerated
     */
    private Integer sjleixingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingType1
     *
     * @mbggenerated
     */
    private Integer sjleixingType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDouble
     *
     * @mbggenerated
     */
    private Double sjleixingDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjleixing.sjleixingDouble1
     *
     * @mbggenerated
     */
    private Double sjleixingDouble1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingId
     *
     * @return the value of t_sjleixing.sjleixingId
     *
     * @mbggenerated
     */
    public Integer getSjleixingId() {
        return sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingId
     *
     * @param sjleixingId the value for t_sjleixing.sjleixingId
     *
     * @mbggenerated
     */
    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingName
     *
     * @return the value of t_sjleixing.sjleixingName
     *
     * @mbggenerated
     */
    public String getSjleixingName() {
        return sjleixingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingName
     *
     * @param sjleixingName the value for t_sjleixing.sjleixingName
     *
     * @mbggenerated
     */
    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingMark
     *
     * @return the value of t_sjleixing.sjleixingMark
     *
     * @mbggenerated
     */
    public String getSjleixingMark() {
        return sjleixingMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingMark
     *
     * @param sjleixingMark the value for t_sjleixing.sjleixingMark
     *
     * @mbggenerated
     */
    public void setSjleixingMark(String sjleixingMark) {
        this.sjleixingMark = sjleixingMark == null ? null : sjleixingMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingMark1
     *
     * @return the value of t_sjleixing.sjleixingMark1
     *
     * @mbggenerated
     */
    public String getSjleixingMark1() {
        return sjleixingMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingMark1
     *
     * @param sjleixingMark1 the value for t_sjleixing.sjleixingMark1
     *
     * @mbggenerated
     */
    public void setSjleixingMark1(String sjleixingMark1) {
        this.sjleixingMark1 = sjleixingMark1 == null ? null : sjleixingMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingMark2
     *
     * @return the value of t_sjleixing.sjleixingMark2
     *
     * @mbggenerated
     */
    public String getSjleixingMark2() {
        return sjleixingMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingMark2
     *
     * @param sjleixingMark2 the value for t_sjleixing.sjleixingMark2
     *
     * @mbggenerated
     */
    public void setSjleixingMark2(String sjleixingMark2) {
        this.sjleixingMark2 = sjleixingMark2 == null ? null : sjleixingMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingPhone
     *
     * @return the value of t_sjleixing.sjleixingPhone
     *
     * @mbggenerated
     */
    public String getSjleixingPhone() {
        return sjleixingPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingPhone
     *
     * @param sjleixingPhone the value for t_sjleixing.sjleixingPhone
     *
     * @mbggenerated
     */
    public void setSjleixingPhone(String sjleixingPhone) {
        this.sjleixingPhone = sjleixingPhone == null ? null : sjleixingPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDizhi
     *
     * @return the value of t_sjleixing.sjleixingDizhi
     *
     * @mbggenerated
     */
    public String getSjleixingDizhi() {
        return sjleixingDizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDizhi
     *
     * @param sjleixingDizhi the value for t_sjleixing.sjleixingDizhi
     *
     * @mbggenerated
     */
    public void setSjleixingDizhi(String sjleixingDizhi) {
        this.sjleixingDizhi = sjleixingDizhi == null ? null : sjleixingDizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDate
     *
     * @return the value of t_sjleixing.sjleixingDate
     *
     * @mbggenerated
     */
    public Date getSjleixingDate() {
        return sjleixingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDate
     *
     * @param sjleixingDate the value for t_sjleixing.sjleixingDate
     *
     * @mbggenerated
     */
    public void setSjleixingDate(Date sjleixingDate) {
        this.sjleixingDate = sjleixingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDate1
     *
     * @return the value of t_sjleixing.sjleixingDate1
     *
     * @mbggenerated
     */
    public Date getSjleixingDate1() {
        return sjleixingDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDate1
     *
     * @param sjleixingDate1 the value for t_sjleixing.sjleixingDate1
     *
     * @mbggenerated
     */
    public void setSjleixingDate1(Date sjleixingDate1) {
        this.sjleixingDate1 = sjleixingDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingType
     *
     * @return the value of t_sjleixing.sjleixingType
     *
     * @mbggenerated
     */
    public Integer getSjleixingType() {
        return sjleixingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingType
     *
     * @param sjleixingType the value for t_sjleixing.sjleixingType
     *
     * @mbggenerated
     */
    public void setSjleixingType(Integer sjleixingType) {
        this.sjleixingType = sjleixingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingType1
     *
     * @return the value of t_sjleixing.sjleixingType1
     *
     * @mbggenerated
     */
    public Integer getSjleixingType1() {
        return sjleixingType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingType1
     *
     * @param sjleixingType1 the value for t_sjleixing.sjleixingType1
     *
     * @mbggenerated
     */
    public void setSjleixingType1(Integer sjleixingType1) {
        this.sjleixingType1 = sjleixingType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDouble
     *
     * @return the value of t_sjleixing.sjleixingDouble
     *
     * @mbggenerated
     */
    public Double getSjleixingDouble() {
        return sjleixingDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDouble
     *
     * @param sjleixingDouble the value for t_sjleixing.sjleixingDouble
     *
     * @mbggenerated
     */
    public void setSjleixingDouble(Double sjleixingDouble) {
        this.sjleixingDouble = sjleixingDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjleixing.sjleixingDouble1
     *
     * @return the value of t_sjleixing.sjleixingDouble1
     *
     * @mbggenerated
     */
    public Double getSjleixingDouble1() {
        return sjleixingDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjleixing.sjleixingDouble1
     *
     * @param sjleixingDouble1 the value for t_sjleixing.sjleixingDouble1
     *
     * @mbggenerated
     */
    public void setSjleixingDouble1(Double sjleixingDouble1) {
        this.sjleixingDouble1 = sjleixingDouble1;
    }
}