package com.model;

import java.util.Date;

public class Sjshaochu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuId
     *
     * @mbggenerated
     */
    private Integer sjshaochuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuName
     *
     * @mbggenerated
     */
    private String sjshaochuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuMark
     *
     * @mbggenerated
     */
    private String sjshaochuMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuMark1
     *
     * @mbggenerated
     */
    private String sjshaochuMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuMark2
     *
     * @mbggenerated
     */
    private String sjshaochuMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuMark3
     *
     * @mbggenerated
     */
    private String sjshaochuMark3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuDate
     *
     * @mbggenerated
     */
    private Date sjshaochuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuDate1
     *
     * @mbggenerated
     */
    private Date sjshaochuDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuZong
     *
     * @mbggenerated
     */
    private Integer sjshaochuZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuZong1
     *
     * @mbggenerated
     */
    private Integer sjshaochuZong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuZong2
     *
     * @mbggenerated
     */
    private Integer sjshaochuZong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuDouble
     *
     * @mbggenerated
     */
    private Double sjshaochuDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuDouble1
     *
     * @mbggenerated
     */
    private Double sjshaochuDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuDouble2
     *
     * @mbggenerated
     */
    private Double sjshaochuDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuType
     *
     * @mbggenerated
     */
    private Integer sjshaochuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuType1
     *
     * @mbggenerated
     */
    private Integer sjshaochuType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuType2
     *
     * @mbggenerated
     */
    private Integer sjshaochuType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjqitaId
     *
     * @mbggenerated
     */
    private Integer sjqitaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjqitaName
     *
     * @mbggenerated
     */
    private String sjqitaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjlaiyuanId
     *
     * @mbggenerated
     */
    private Integer sjlaiyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjlaiyuanName
     *
     * @mbggenerated
     */
    private String sjlaiyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuImg
     *
     * @mbggenerated
     */
    private String sjshaochuImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjshaochuImgName
     *
     * @mbggenerated
     */
    private String sjshaochuImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.shujuId
     *
     * @mbggenerated
     */
    private Integer shujuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.shujuName
     *
     * @mbggenerated
     */
    private String shujuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjleixingId
     *
     * @mbggenerated
     */
    private Integer sjleixingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjleixingName
     *
     * @mbggenerated
     */
    private String sjleixingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjxingtaiId
     *
     * @mbggenerated
     */
    private Integer sjxingtaiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.sjxingtaiName
     *
     * @mbggenerated
     */
    private String sjxingtaiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.yonghuId
     *
     * @mbggenerated
     */
    private Integer yonghuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.yonghuName
     *
     * @mbggenerated
     */
    private String yonghuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.byumenId
     *
     * @mbggenerated
     */
    private Integer byumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.byumenName
     *
     * @mbggenerated
     */
    private String byumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.byuyuanId
     *
     * @mbggenerated
     */
    private Integer byuyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.byuyuanName
     *
     * @mbggenerated
     */
    private String byuyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.byuzhiId
     *
     * @mbggenerated
     */
    private Integer byuzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.byuzhiName
     *
     * @mbggenerated
     */
    private String byuzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.yhroleId
     *
     * @mbggenerated
     */
    private Integer yhroleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjshaochu.yhroleName
     *
     * @mbggenerated
     */
    private String yhroleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuId
     *
     * @return the value of t_sjshaochu.sjshaochuId
     *
     * @mbggenerated
     */
    public Integer getSjshaochuId() {
        return sjshaochuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuId
     *
     * @param sjshaochuId the value for t_sjshaochu.sjshaochuId
     *
     * @mbggenerated
     */
    public void setSjshaochuId(Integer sjshaochuId) {
        this.sjshaochuId = sjshaochuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuName
     *
     * @return the value of t_sjshaochu.sjshaochuName
     *
     * @mbggenerated
     */
    public String getSjshaochuName() {
        return sjshaochuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuName
     *
     * @param sjshaochuName the value for t_sjshaochu.sjshaochuName
     *
     * @mbggenerated
     */
    public void setSjshaochuName(String sjshaochuName) {
        this.sjshaochuName = sjshaochuName == null ? null : sjshaochuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuMark
     *
     * @return the value of t_sjshaochu.sjshaochuMark
     *
     * @mbggenerated
     */
    public String getSjshaochuMark() {
        return sjshaochuMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuMark
     *
     * @param sjshaochuMark the value for t_sjshaochu.sjshaochuMark
     *
     * @mbggenerated
     */
    public void setSjshaochuMark(String sjshaochuMark) {
        this.sjshaochuMark = sjshaochuMark == null ? null : sjshaochuMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuMark1
     *
     * @return the value of t_sjshaochu.sjshaochuMark1
     *
     * @mbggenerated
     */
    public String getSjshaochuMark1() {
        return sjshaochuMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuMark1
     *
     * @param sjshaochuMark1 the value for t_sjshaochu.sjshaochuMark1
     *
     * @mbggenerated
     */
    public void setSjshaochuMark1(String sjshaochuMark1) {
        this.sjshaochuMark1 = sjshaochuMark1 == null ? null : sjshaochuMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuMark2
     *
     * @return the value of t_sjshaochu.sjshaochuMark2
     *
     * @mbggenerated
     */
    public String getSjshaochuMark2() {
        return sjshaochuMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuMark2
     *
     * @param sjshaochuMark2 the value for t_sjshaochu.sjshaochuMark2
     *
     * @mbggenerated
     */
    public void setSjshaochuMark2(String sjshaochuMark2) {
        this.sjshaochuMark2 = sjshaochuMark2 == null ? null : sjshaochuMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuMark3
     *
     * @return the value of t_sjshaochu.sjshaochuMark3
     *
     * @mbggenerated
     */
    public String getSjshaochuMark3() {
        return sjshaochuMark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuMark3
     *
     * @param sjshaochuMark3 the value for t_sjshaochu.sjshaochuMark3
     *
     * @mbggenerated
     */
    public void setSjshaochuMark3(String sjshaochuMark3) {
        this.sjshaochuMark3 = sjshaochuMark3 == null ? null : sjshaochuMark3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuDate
     *
     * @return the value of t_sjshaochu.sjshaochuDate
     *
     * @mbggenerated
     */
    public Date getSjshaochuDate() {
        return sjshaochuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuDate
     *
     * @param sjshaochuDate the value for t_sjshaochu.sjshaochuDate
     *
     * @mbggenerated
     */
    public void setSjshaochuDate(Date sjshaochuDate) {
        this.sjshaochuDate = sjshaochuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuDate1
     *
     * @return the value of t_sjshaochu.sjshaochuDate1
     *
     * @mbggenerated
     */
    public Date getSjshaochuDate1() {
        return sjshaochuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuDate1
     *
     * @param sjshaochuDate1 the value for t_sjshaochu.sjshaochuDate1
     *
     * @mbggenerated
     */
    public void setSjshaochuDate1(Date sjshaochuDate1) {
        this.sjshaochuDate1 = sjshaochuDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuZong
     *
     * @return the value of t_sjshaochu.sjshaochuZong
     *
     * @mbggenerated
     */
    public Integer getSjshaochuZong() {
        return sjshaochuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuZong
     *
     * @param sjshaochuZong the value for t_sjshaochu.sjshaochuZong
     *
     * @mbggenerated
     */
    public void setSjshaochuZong(Integer sjshaochuZong) {
        this.sjshaochuZong = sjshaochuZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuZong1
     *
     * @return the value of t_sjshaochu.sjshaochuZong1
     *
     * @mbggenerated
     */
    public Integer getSjshaochuZong1() {
        return sjshaochuZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuZong1
     *
     * @param sjshaochuZong1 the value for t_sjshaochu.sjshaochuZong1
     *
     * @mbggenerated
     */
    public void setSjshaochuZong1(Integer sjshaochuZong1) {
        this.sjshaochuZong1 = sjshaochuZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuZong2
     *
     * @return the value of t_sjshaochu.sjshaochuZong2
     *
     * @mbggenerated
     */
    public Integer getSjshaochuZong2() {
        return sjshaochuZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuZong2
     *
     * @param sjshaochuZong2 the value for t_sjshaochu.sjshaochuZong2
     *
     * @mbggenerated
     */
    public void setSjshaochuZong2(Integer sjshaochuZong2) {
        this.sjshaochuZong2 = sjshaochuZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuDouble
     *
     * @return the value of t_sjshaochu.sjshaochuDouble
     *
     * @mbggenerated
     */
    public Double getSjshaochuDouble() {
        return sjshaochuDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuDouble
     *
     * @param sjshaochuDouble the value for t_sjshaochu.sjshaochuDouble
     *
     * @mbggenerated
     */
    public void setSjshaochuDouble(Double sjshaochuDouble) {
        this.sjshaochuDouble = sjshaochuDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuDouble1
     *
     * @return the value of t_sjshaochu.sjshaochuDouble1
     *
     * @mbggenerated
     */
    public Double getSjshaochuDouble1() {
        return sjshaochuDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuDouble1
     *
     * @param sjshaochuDouble1 the value for t_sjshaochu.sjshaochuDouble1
     *
     * @mbggenerated
     */
    public void setSjshaochuDouble1(Double sjshaochuDouble1) {
        this.sjshaochuDouble1 = sjshaochuDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuDouble2
     *
     * @return the value of t_sjshaochu.sjshaochuDouble2
     *
     * @mbggenerated
     */
    public Double getSjshaochuDouble2() {
        return sjshaochuDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuDouble2
     *
     * @param sjshaochuDouble2 the value for t_sjshaochu.sjshaochuDouble2
     *
     * @mbggenerated
     */
    public void setSjshaochuDouble2(Double sjshaochuDouble2) {
        this.sjshaochuDouble2 = sjshaochuDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuType
     *
     * @return the value of t_sjshaochu.sjshaochuType
     *
     * @mbggenerated
     */
    public Integer getSjshaochuType() {
        return sjshaochuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuType
     *
     * @param sjshaochuType the value for t_sjshaochu.sjshaochuType
     *
     * @mbggenerated
     */
    public void setSjshaochuType(Integer sjshaochuType) {
        this.sjshaochuType = sjshaochuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuType1
     *
     * @return the value of t_sjshaochu.sjshaochuType1
     *
     * @mbggenerated
     */
    public Integer getSjshaochuType1() {
        return sjshaochuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuType1
     *
     * @param sjshaochuType1 the value for t_sjshaochu.sjshaochuType1
     *
     * @mbggenerated
     */
    public void setSjshaochuType1(Integer sjshaochuType1) {
        this.sjshaochuType1 = sjshaochuType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuType2
     *
     * @return the value of t_sjshaochu.sjshaochuType2
     *
     * @mbggenerated
     */
    public Integer getSjshaochuType2() {
        return sjshaochuType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuType2
     *
     * @param sjshaochuType2 the value for t_sjshaochu.sjshaochuType2
     *
     * @mbggenerated
     */
    public void setSjshaochuType2(Integer sjshaochuType2) {
        this.sjshaochuType2 = sjshaochuType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjqitaId
     *
     * @return the value of t_sjshaochu.sjqitaId
     *
     * @mbggenerated
     */
    public Integer getSjqitaId() {
        return sjqitaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjqitaId
     *
     * @param sjqitaId the value for t_sjshaochu.sjqitaId
     *
     * @mbggenerated
     */
    public void setSjqitaId(Integer sjqitaId) {
        this.sjqitaId = sjqitaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjqitaName
     *
     * @return the value of t_sjshaochu.sjqitaName
     *
     * @mbggenerated
     */
    public String getSjqitaName() {
        return sjqitaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjqitaName
     *
     * @param sjqitaName the value for t_sjshaochu.sjqitaName
     *
     * @mbggenerated
     */
    public void setSjqitaName(String sjqitaName) {
        this.sjqitaName = sjqitaName == null ? null : sjqitaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjlaiyuanId
     *
     * @return the value of t_sjshaochu.sjlaiyuanId
     *
     * @mbggenerated
     */
    public Integer getSjlaiyuanId() {
        return sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjlaiyuanId
     *
     * @param sjlaiyuanId the value for t_sjshaochu.sjlaiyuanId
     *
     * @mbggenerated
     */
    public void setSjlaiyuanId(Integer sjlaiyuanId) {
        this.sjlaiyuanId = sjlaiyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjlaiyuanName
     *
     * @return the value of t_sjshaochu.sjlaiyuanName
     *
     * @mbggenerated
     */
    public String getSjlaiyuanName() {
        return sjlaiyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjlaiyuanName
     *
     * @param sjlaiyuanName the value for t_sjshaochu.sjlaiyuanName
     *
     * @mbggenerated
     */
    public void setSjlaiyuanName(String sjlaiyuanName) {
        this.sjlaiyuanName = sjlaiyuanName == null ? null : sjlaiyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuImg
     *
     * @return the value of t_sjshaochu.sjshaochuImg
     *
     * @mbggenerated
     */
    public String getSjshaochuImg() {
        return sjshaochuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuImg
     *
     * @param sjshaochuImg the value for t_sjshaochu.sjshaochuImg
     *
     * @mbggenerated
     */
    public void setSjshaochuImg(String sjshaochuImg) {
        this.sjshaochuImg = sjshaochuImg == null ? null : sjshaochuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjshaochuImgName
     *
     * @return the value of t_sjshaochu.sjshaochuImgName
     *
     * @mbggenerated
     */
    public String getSjshaochuImgName() {
        return sjshaochuImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjshaochuImgName
     *
     * @param sjshaochuImgName the value for t_sjshaochu.sjshaochuImgName
     *
     * @mbggenerated
     */
    public void setSjshaochuImgName(String sjshaochuImgName) {
        this.sjshaochuImgName = sjshaochuImgName == null ? null : sjshaochuImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.shujuId
     *
     * @return the value of t_sjshaochu.shujuId
     *
     * @mbggenerated
     */
    public Integer getShujuId() {
        return shujuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.shujuId
     *
     * @param shujuId the value for t_sjshaochu.shujuId
     *
     * @mbggenerated
     */
    public void setShujuId(Integer shujuId) {
        this.shujuId = shujuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.shujuName
     *
     * @return the value of t_sjshaochu.shujuName
     *
     * @mbggenerated
     */
    public String getShujuName() {
        return shujuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.shujuName
     *
     * @param shujuName the value for t_sjshaochu.shujuName
     *
     * @mbggenerated
     */
    public void setShujuName(String shujuName) {
        this.shujuName = shujuName == null ? null : shujuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjleixingId
     *
     * @return the value of t_sjshaochu.sjleixingId
     *
     * @mbggenerated
     */
    public Integer getSjleixingId() {
        return sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjleixingId
     *
     * @param sjleixingId the value for t_sjshaochu.sjleixingId
     *
     * @mbggenerated
     */
    public void setSjleixingId(Integer sjleixingId) {
        this.sjleixingId = sjleixingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjleixingName
     *
     * @return the value of t_sjshaochu.sjleixingName
     *
     * @mbggenerated
     */
    public String getSjleixingName() {
        return sjleixingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjleixingName
     *
     * @param sjleixingName the value for t_sjshaochu.sjleixingName
     *
     * @mbggenerated
     */
    public void setSjleixingName(String sjleixingName) {
        this.sjleixingName = sjleixingName == null ? null : sjleixingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjxingtaiId
     *
     * @return the value of t_sjshaochu.sjxingtaiId
     *
     * @mbggenerated
     */
    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjxingtaiId
     *
     * @param sjxingtaiId the value for t_sjshaochu.sjxingtaiId
     *
     * @mbggenerated
     */
    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.sjxingtaiName
     *
     * @return the value of t_sjshaochu.sjxingtaiName
     *
     * @mbggenerated
     */
    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.sjxingtaiName
     *
     * @param sjxingtaiName the value for t_sjshaochu.sjxingtaiName
     *
     * @mbggenerated
     */
    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.userId
     *
     * @return the value of t_sjshaochu.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.userId
     *
     * @param userId the value for t_sjshaochu.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.userName
     *
     * @return the value of t_sjshaochu.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.userName
     *
     * @param userName the value for t_sjshaochu.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.bumenId
     *
     * @return the value of t_sjshaochu.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.bumenId
     *
     * @param bumenId the value for t_sjshaochu.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.bumenName
     *
     * @return the value of t_sjshaochu.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.bumenName
     *
     * @param bumenName the value for t_sjshaochu.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.buyuanId
     *
     * @return the value of t_sjshaochu.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.buyuanId
     *
     * @param buyuanId the value for t_sjshaochu.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.buyuanName
     *
     * @return the value of t_sjshaochu.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.buyuanName
     *
     * @param buyuanName the value for t_sjshaochu.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.yonghuId
     *
     * @return the value of t_sjshaochu.yonghuId
     *
     * @mbggenerated
     */
    public Integer getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.yonghuId
     *
     * @param yonghuId the value for t_sjshaochu.yonghuId
     *
     * @mbggenerated
     */
    public void setYonghuId(Integer yonghuId) {
        this.yonghuId = yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.yonghuName
     *
     * @return the value of t_sjshaochu.yonghuName
     *
     * @mbggenerated
     */
    public String getYonghuName() {
        return yonghuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.yonghuName
     *
     * @param yonghuName the value for t_sjshaochu.yonghuName
     *
     * @mbggenerated
     */
    public void setYonghuName(String yonghuName) {
        this.yonghuName = yonghuName == null ? null : yonghuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.byumenId
     *
     * @return the value of t_sjshaochu.byumenId
     *
     * @mbggenerated
     */
    public Integer getByumenId() {
        return byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.byumenId
     *
     * @param byumenId the value for t_sjshaochu.byumenId
     *
     * @mbggenerated
     */
    public void setByumenId(Integer byumenId) {
        this.byumenId = byumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.byumenName
     *
     * @return the value of t_sjshaochu.byumenName
     *
     * @mbggenerated
     */
    public String getByumenName() {
        return byumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.byumenName
     *
     * @param byumenName the value for t_sjshaochu.byumenName
     *
     * @mbggenerated
     */
    public void setByumenName(String byumenName) {
        this.byumenName = byumenName == null ? null : byumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.byuyuanId
     *
     * @return the value of t_sjshaochu.byuyuanId
     *
     * @mbggenerated
     */
    public Integer getByuyuanId() {
        return byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.byuyuanId
     *
     * @param byuyuanId the value for t_sjshaochu.byuyuanId
     *
     * @mbggenerated
     */
    public void setByuyuanId(Integer byuyuanId) {
        this.byuyuanId = byuyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.byuyuanName
     *
     * @return the value of t_sjshaochu.byuyuanName
     *
     * @mbggenerated
     */
    public String getByuyuanName() {
        return byuyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.byuyuanName
     *
     * @param byuyuanName the value for t_sjshaochu.byuyuanName
     *
     * @mbggenerated
     */
    public void setByuyuanName(String byuyuanName) {
        this.byuyuanName = byuyuanName == null ? null : byuyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.buzhiId
     *
     * @return the value of t_sjshaochu.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.buzhiId
     *
     * @param buzhiId the value for t_sjshaochu.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.buzhiName
     *
     * @return the value of t_sjshaochu.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.buzhiName
     *
     * @param buzhiName the value for t_sjshaochu.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.roleId
     *
     * @return the value of t_sjshaochu.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.roleId
     *
     * @param roleId the value for t_sjshaochu.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.roleName
     *
     * @return the value of t_sjshaochu.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.roleName
     *
     * @param roleName the value for t_sjshaochu.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.byuzhiId
     *
     * @return the value of t_sjshaochu.byuzhiId
     *
     * @mbggenerated
     */
    public Integer getByuzhiId() {
        return byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.byuzhiId
     *
     * @param byuzhiId the value for t_sjshaochu.byuzhiId
     *
     * @mbggenerated
     */
    public void setByuzhiId(Integer byuzhiId) {
        this.byuzhiId = byuzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.byuzhiName
     *
     * @return the value of t_sjshaochu.byuzhiName
     *
     * @mbggenerated
     */
    public String getByuzhiName() {
        return byuzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.byuzhiName
     *
     * @param byuzhiName the value for t_sjshaochu.byuzhiName
     *
     * @mbggenerated
     */
    public void setByuzhiName(String byuzhiName) {
        this.byuzhiName = byuzhiName == null ? null : byuzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.yhroleId
     *
     * @return the value of t_sjshaochu.yhroleId
     *
     * @mbggenerated
     */
    public Integer getYhroleId() {
        return yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.yhroleId
     *
     * @param yhroleId the value for t_sjshaochu.yhroleId
     *
     * @mbggenerated
     */
    public void setYhroleId(Integer yhroleId) {
        this.yhroleId = yhroleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjshaochu.yhroleName
     *
     * @return the value of t_sjshaochu.yhroleName
     *
     * @mbggenerated
     */
    public String getYhroleName() {
        return yhroleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjshaochu.yhroleName
     *
     * @param yhroleName the value for t_sjshaochu.yhroleName
     *
     * @mbggenerated
     */
    public void setYhroleName(String yhroleName) {
        this.yhroleName = yhroleName == null ? null : yhroleName.trim();
    }
}