package com.model;

import java.util.Date;

public class Sjxingtai {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiId
     *
     * @mbggenerated
     */
    private Integer sjxingtaiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiName
     *
     * @mbggenerated
     */
    private String sjxingtaiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiMark
     *
     * @mbggenerated
     */
    private String sjxingtaiMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiMark1
     *
     * @mbggenerated
     */
    private String sjxingtaiMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiMark2
     *
     * @mbggenerated
     */
    private String sjxingtaiMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiPhone
     *
     * @mbggenerated
     */
    private String sjxingtaiPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiDizhi
     *
     * @mbggenerated
     */
    private String sjxingtaiDizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiDate
     *
     * @mbggenerated
     */
    private Date sjxingtaiDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiDate1
     *
     * @mbggenerated
     */
    private Date sjxingtaiDate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiType
     *
     * @mbggenerated
     */
    private Integer sjxingtaiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiType1
     *
     * @mbggenerated
     */
    private Integer sjxingtaiType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiDouble
     *
     * @mbggenerated
     */
    private Double sjxingtaiDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sjxingtai.sjxingtaiDouble1
     *
     * @mbggenerated
     */
    private Double sjxingtaiDouble1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiId
     *
     * @return the value of t_sjxingtai.sjxingtaiId
     *
     * @mbggenerated
     */
    public Integer getSjxingtaiId() {
        return sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiId
     *
     * @param sjxingtaiId the value for t_sjxingtai.sjxingtaiId
     *
     * @mbggenerated
     */
    public void setSjxingtaiId(Integer sjxingtaiId) {
        this.sjxingtaiId = sjxingtaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiName
     *
     * @return the value of t_sjxingtai.sjxingtaiName
     *
     * @mbggenerated
     */
    public String getSjxingtaiName() {
        return sjxingtaiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiName
     *
     * @param sjxingtaiName the value for t_sjxingtai.sjxingtaiName
     *
     * @mbggenerated
     */
    public void setSjxingtaiName(String sjxingtaiName) {
        this.sjxingtaiName = sjxingtaiName == null ? null : sjxingtaiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiMark
     *
     * @return the value of t_sjxingtai.sjxingtaiMark
     *
     * @mbggenerated
     */
    public String getSjxingtaiMark() {
        return sjxingtaiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiMark
     *
     * @param sjxingtaiMark the value for t_sjxingtai.sjxingtaiMark
     *
     * @mbggenerated
     */
    public void setSjxingtaiMark(String sjxingtaiMark) {
        this.sjxingtaiMark = sjxingtaiMark == null ? null : sjxingtaiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiMark1
     *
     * @return the value of t_sjxingtai.sjxingtaiMark1
     *
     * @mbggenerated
     */
    public String getSjxingtaiMark1() {
        return sjxingtaiMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiMark1
     *
     * @param sjxingtaiMark1 the value for t_sjxingtai.sjxingtaiMark1
     *
     * @mbggenerated
     */
    public void setSjxingtaiMark1(String sjxingtaiMark1) {
        this.sjxingtaiMark1 = sjxingtaiMark1 == null ? null : sjxingtaiMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiMark2
     *
     * @return the value of t_sjxingtai.sjxingtaiMark2
     *
     * @mbggenerated
     */
    public String getSjxingtaiMark2() {
        return sjxingtaiMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiMark2
     *
     * @param sjxingtaiMark2 the value for t_sjxingtai.sjxingtaiMark2
     *
     * @mbggenerated
     */
    public void setSjxingtaiMark2(String sjxingtaiMark2) {
        this.sjxingtaiMark2 = sjxingtaiMark2 == null ? null : sjxingtaiMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiPhone
     *
     * @return the value of t_sjxingtai.sjxingtaiPhone
     *
     * @mbggenerated
     */
    public String getSjxingtaiPhone() {
        return sjxingtaiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiPhone
     *
     * @param sjxingtaiPhone the value for t_sjxingtai.sjxingtaiPhone
     *
     * @mbggenerated
     */
    public void setSjxingtaiPhone(String sjxingtaiPhone) {
        this.sjxingtaiPhone = sjxingtaiPhone == null ? null : sjxingtaiPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiDizhi
     *
     * @return the value of t_sjxingtai.sjxingtaiDizhi
     *
     * @mbggenerated
     */
    public String getSjxingtaiDizhi() {
        return sjxingtaiDizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiDizhi
     *
     * @param sjxingtaiDizhi the value for t_sjxingtai.sjxingtaiDizhi
     *
     * @mbggenerated
     */
    public void setSjxingtaiDizhi(String sjxingtaiDizhi) {
        this.sjxingtaiDizhi = sjxingtaiDizhi == null ? null : sjxingtaiDizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiDate
     *
     * @return the value of t_sjxingtai.sjxingtaiDate
     *
     * @mbggenerated
     */
    public Date getSjxingtaiDate() {
        return sjxingtaiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiDate
     *
     * @param sjxingtaiDate the value for t_sjxingtai.sjxingtaiDate
     *
     * @mbggenerated
     */
    public void setSjxingtaiDate(Date sjxingtaiDate) {
        this.sjxingtaiDate = sjxingtaiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiDate1
     *
     * @return the value of t_sjxingtai.sjxingtaiDate1
     *
     * @mbggenerated
     */
    public Date getSjxingtaiDate1() {
        return sjxingtaiDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiDate1
     *
     * @param sjxingtaiDate1 the value for t_sjxingtai.sjxingtaiDate1
     *
     * @mbggenerated
     */
    public void setSjxingtaiDate1(Date sjxingtaiDate1) {
        this.sjxingtaiDate1 = sjxingtaiDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiType
     *
     * @return the value of t_sjxingtai.sjxingtaiType
     *
     * @mbggenerated
     */
    public Integer getSjxingtaiType() {
        return sjxingtaiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiType
     *
     * @param sjxingtaiType the value for t_sjxingtai.sjxingtaiType
     *
     * @mbggenerated
     */
    public void setSjxingtaiType(Integer sjxingtaiType) {
        this.sjxingtaiType = sjxingtaiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiType1
     *
     * @return the value of t_sjxingtai.sjxingtaiType1
     *
     * @mbggenerated
     */
    public Integer getSjxingtaiType1() {
        return sjxingtaiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiType1
     *
     * @param sjxingtaiType1 the value for t_sjxingtai.sjxingtaiType1
     *
     * @mbggenerated
     */
    public void setSjxingtaiType1(Integer sjxingtaiType1) {
        this.sjxingtaiType1 = sjxingtaiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiDouble
     *
     * @return the value of t_sjxingtai.sjxingtaiDouble
     *
     * @mbggenerated
     */
    public Double getSjxingtaiDouble() {
        return sjxingtaiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiDouble
     *
     * @param sjxingtaiDouble the value for t_sjxingtai.sjxingtaiDouble
     *
     * @mbggenerated
     */
    public void setSjxingtaiDouble(Double sjxingtaiDouble) {
        this.sjxingtaiDouble = sjxingtaiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sjxingtai.sjxingtaiDouble1
     *
     * @return the value of t_sjxingtai.sjxingtaiDouble1
     *
     * @mbggenerated
     */
    public Double getSjxingtaiDouble1() {
        return sjxingtaiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sjxingtai.sjxingtaiDouble1
     *
     * @param sjxingtaiDouble1 the value for t_sjxingtai.sjxingtaiDouble1
     *
     * @mbggenerated
     */
    public void setSjxingtaiDouble1(Double sjxingtaiDouble1) {
        this.sjxingtaiDouble1 = sjxingtaiDouble1;
    }
}