package com.model;

import java.util.Date;

public class Uxinxi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiId
     *
     * @mbggenerated
     */
    private Integer uxinxiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiName
     *
     * @mbggenerated
     */
    private String uxinxiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiMark
     *
     * @mbggenerated
     */
    private String uxinxiMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiMark1
     *
     * @mbggenerated
     */
    private String uxinxiMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiMark2
     *
     * @mbggenerated
     */
    private String uxinxiMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiImg
     *
     * @mbggenerated
     */
    private String uxinxiImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiImgName
     *
     * @mbggenerated
     */
    private String uxinxiImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiDate
     *
     * @mbggenerated
     */
    private Date uxinxiDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiZong
     *
     * @mbggenerated
     */
    private Integer uxinxiZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiZong1
     *
     * @mbggenerated
     */
    private Integer uxinxiZong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiZong2
     *
     * @mbggenerated
     */
    private Integer uxinxiZong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiDouble
     *
     * @mbggenerated
     */
    private Double uxinxiDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiDouble1
     *
     * @mbggenerated
     */
    private Double uxinxiDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiDouble2
     *
     * @mbggenerated
     */
    private Double uxinxiDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiType
     *
     * @mbggenerated
     */
    private Integer uxinxiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiType1
     *
     * @mbggenerated
     */
    private Integer uxinxiType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxinxiType2
     *
     * @mbggenerated
     */
    private Integer uxinxiType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxtypeId
     *
     * @mbggenerated
     */
    private Integer uxtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.uxtypeName
     *
     * @mbggenerated
     */
    private String uxtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxinxi.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiId
     *
     * @return the value of t_uxinxi.uxinxiId
     *
     * @mbggenerated
     */
    public Integer getUxinxiId() {
        return uxinxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiId
     *
     * @param uxinxiId the value for t_uxinxi.uxinxiId
     *
     * @mbggenerated
     */
    public void setUxinxiId(Integer uxinxiId) {
        this.uxinxiId = uxinxiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiName
     *
     * @return the value of t_uxinxi.uxinxiName
     *
     * @mbggenerated
     */
    public String getUxinxiName() {
        return uxinxiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiName
     *
     * @param uxinxiName the value for t_uxinxi.uxinxiName
     *
     * @mbggenerated
     */
    public void setUxinxiName(String uxinxiName) {
        this.uxinxiName = uxinxiName == null ? null : uxinxiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiMark
     *
     * @return the value of t_uxinxi.uxinxiMark
     *
     * @mbggenerated
     */
    public String getUxinxiMark() {
        return uxinxiMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiMark
     *
     * @param uxinxiMark the value for t_uxinxi.uxinxiMark
     *
     * @mbggenerated
     */
    public void setUxinxiMark(String uxinxiMark) {
        this.uxinxiMark = uxinxiMark == null ? null : uxinxiMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiMark1
     *
     * @return the value of t_uxinxi.uxinxiMark1
     *
     * @mbggenerated
     */
    public String getUxinxiMark1() {
        return uxinxiMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiMark1
     *
     * @param uxinxiMark1 the value for t_uxinxi.uxinxiMark1
     *
     * @mbggenerated
     */
    public void setUxinxiMark1(String uxinxiMark1) {
        this.uxinxiMark1 = uxinxiMark1 == null ? null : uxinxiMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiMark2
     *
     * @return the value of t_uxinxi.uxinxiMark2
     *
     * @mbggenerated
     */
    public String getUxinxiMark2() {
        return uxinxiMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiMark2
     *
     * @param uxinxiMark2 the value for t_uxinxi.uxinxiMark2
     *
     * @mbggenerated
     */
    public void setUxinxiMark2(String uxinxiMark2) {
        this.uxinxiMark2 = uxinxiMark2 == null ? null : uxinxiMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiImg
     *
     * @return the value of t_uxinxi.uxinxiImg
     *
     * @mbggenerated
     */
    public String getUxinxiImg() {
        return uxinxiImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiImg
     *
     * @param uxinxiImg the value for t_uxinxi.uxinxiImg
     *
     * @mbggenerated
     */
    public void setUxinxiImg(String uxinxiImg) {
        this.uxinxiImg = uxinxiImg == null ? null : uxinxiImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiImgName
     *
     * @return the value of t_uxinxi.uxinxiImgName
     *
     * @mbggenerated
     */
    public String getUxinxiImgName() {
        return uxinxiImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiImgName
     *
     * @param uxinxiImgName the value for t_uxinxi.uxinxiImgName
     *
     * @mbggenerated
     */
    public void setUxinxiImgName(String uxinxiImgName) {
        this.uxinxiImgName = uxinxiImgName == null ? null : uxinxiImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiDate
     *
     * @return the value of t_uxinxi.uxinxiDate
     *
     * @mbggenerated
     */
    public Date getUxinxiDate() {
        return uxinxiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiDate
     *
     * @param uxinxiDate the value for t_uxinxi.uxinxiDate
     *
     * @mbggenerated
     */
    public void setUxinxiDate(Date uxinxiDate) {
        this.uxinxiDate = uxinxiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiZong
     *
     * @return the value of t_uxinxi.uxinxiZong
     *
     * @mbggenerated
     */
    public Integer getUxinxiZong() {
        return uxinxiZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiZong
     *
     * @param uxinxiZong the value for t_uxinxi.uxinxiZong
     *
     * @mbggenerated
     */
    public void setUxinxiZong(Integer uxinxiZong) {
        this.uxinxiZong = uxinxiZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiZong1
     *
     * @return the value of t_uxinxi.uxinxiZong1
     *
     * @mbggenerated
     */
    public Integer getUxinxiZong1() {
        return uxinxiZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiZong1
     *
     * @param uxinxiZong1 the value for t_uxinxi.uxinxiZong1
     *
     * @mbggenerated
     */
    public void setUxinxiZong1(Integer uxinxiZong1) {
        this.uxinxiZong1 = uxinxiZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiZong2
     *
     * @return the value of t_uxinxi.uxinxiZong2
     *
     * @mbggenerated
     */
    public Integer getUxinxiZong2() {
        return uxinxiZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiZong2
     *
     * @param uxinxiZong2 the value for t_uxinxi.uxinxiZong2
     *
     * @mbggenerated
     */
    public void setUxinxiZong2(Integer uxinxiZong2) {
        this.uxinxiZong2 = uxinxiZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiDouble
     *
     * @return the value of t_uxinxi.uxinxiDouble
     *
     * @mbggenerated
     */
    public Double getUxinxiDouble() {
        return uxinxiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiDouble
     *
     * @param uxinxiDouble the value for t_uxinxi.uxinxiDouble
     *
     * @mbggenerated
     */
    public void setUxinxiDouble(Double uxinxiDouble) {
        this.uxinxiDouble = uxinxiDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiDouble1
     *
     * @return the value of t_uxinxi.uxinxiDouble1
     *
     * @mbggenerated
     */
    public Double getUxinxiDouble1() {
        return uxinxiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiDouble1
     *
     * @param uxinxiDouble1 the value for t_uxinxi.uxinxiDouble1
     *
     * @mbggenerated
     */
    public void setUxinxiDouble1(Double uxinxiDouble1) {
        this.uxinxiDouble1 = uxinxiDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiDouble2
     *
     * @return the value of t_uxinxi.uxinxiDouble2
     *
     * @mbggenerated
     */
    public Double getUxinxiDouble2() {
        return uxinxiDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiDouble2
     *
     * @param uxinxiDouble2 the value for t_uxinxi.uxinxiDouble2
     *
     * @mbggenerated
     */
    public void setUxinxiDouble2(Double uxinxiDouble2) {
        this.uxinxiDouble2 = uxinxiDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiType
     *
     * @return the value of t_uxinxi.uxinxiType
     *
     * @mbggenerated
     */
    public Integer getUxinxiType() {
        return uxinxiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiType
     *
     * @param uxinxiType the value for t_uxinxi.uxinxiType
     *
     * @mbggenerated
     */
    public void setUxinxiType(Integer uxinxiType) {
        this.uxinxiType = uxinxiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiType1
     *
     * @return the value of t_uxinxi.uxinxiType1
     *
     * @mbggenerated
     */
    public Integer getUxinxiType1() {
        return uxinxiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiType1
     *
     * @param uxinxiType1 the value for t_uxinxi.uxinxiType1
     *
     * @mbggenerated
     */
    public void setUxinxiType1(Integer uxinxiType1) {
        this.uxinxiType1 = uxinxiType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxinxiType2
     *
     * @return the value of t_uxinxi.uxinxiType2
     *
     * @mbggenerated
     */
    public Integer getUxinxiType2() {
        return uxinxiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxinxiType2
     *
     * @param uxinxiType2 the value for t_uxinxi.uxinxiType2
     *
     * @mbggenerated
     */
    public void setUxinxiType2(Integer uxinxiType2) {
        this.uxinxiType2 = uxinxiType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxtypeId
     *
     * @return the value of t_uxinxi.uxtypeId
     *
     * @mbggenerated
     */
    public Integer getUxtypeId() {
        return uxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxtypeId
     *
     * @param uxtypeId the value for t_uxinxi.uxtypeId
     *
     * @mbggenerated
     */
    public void setUxtypeId(Integer uxtypeId) {
        this.uxtypeId = uxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.uxtypeName
     *
     * @return the value of t_uxinxi.uxtypeName
     *
     * @mbggenerated
     */
    public String getUxtypeName() {
        return uxtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.uxtypeName
     *
     * @param uxtypeName the value for t_uxinxi.uxtypeName
     *
     * @mbggenerated
     */
    public void setUxtypeName(String uxtypeName) {
        this.uxtypeName = uxtypeName == null ? null : uxtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.userId
     *
     * @return the value of t_uxinxi.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.userId
     *
     * @param userId the value for t_uxinxi.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.userName
     *
     * @return the value of t_uxinxi.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.userName
     *
     * @param userName the value for t_uxinxi.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.bumenId
     *
     * @return the value of t_uxinxi.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.bumenId
     *
     * @param bumenId the value for t_uxinxi.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.bumenName
     *
     * @return the value of t_uxinxi.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.bumenName
     *
     * @param bumenName the value for t_uxinxi.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.buyuanId
     *
     * @return the value of t_uxinxi.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.buyuanId
     *
     * @param buyuanId the value for t_uxinxi.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.buyuanName
     *
     * @return the value of t_uxinxi.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.buyuanName
     *
     * @param buyuanName the value for t_uxinxi.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.buzhiId
     *
     * @return the value of t_uxinxi.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.buzhiId
     *
     * @param buzhiId the value for t_uxinxi.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.buzhiName
     *
     * @return the value of t_uxinxi.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.buzhiName
     *
     * @param buzhiName the value for t_uxinxi.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.roleId
     *
     * @return the value of t_uxinxi.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.roleId
     *
     * @param roleId the value for t_uxinxi.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxinxi.roleName
     *
     * @return the value of t_uxinxi.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxinxi.roleName
     *
     * @param roleName the value for t_uxinxi.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}