package com.model;

public class Uxtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxtype.uxtypeId
     *
     * @mbggenerated
     */
    private Integer uxtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxtype.uxtypeName
     *
     * @mbggenerated
     */
    private String uxtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uxtype.uxtypeMark
     *
     * @mbggenerated
     */
    private String uxtypeMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxtype.uxtypeId
     *
     * @return the value of t_uxtype.uxtypeId
     *
     * @mbggenerated
     */
    public Integer getUxtypeId() {
        return uxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxtype.uxtypeId
     *
     * @param uxtypeId the value for t_uxtype.uxtypeId
     *
     * @mbggenerated
     */
    public void setUxtypeId(Integer uxtypeId) {
        this.uxtypeId = uxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxtype.uxtypeName
     *
     * @return the value of t_uxtype.uxtypeName
     *
     * @mbggenerated
     */
    public String getUxtypeName() {
        return uxtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxtype.uxtypeName
     *
     * @param uxtypeName the value for t_uxtype.uxtypeName
     *
     * @mbggenerated
     */
    public void setUxtypeName(String uxtypeName) {
        this.uxtypeName = uxtypeName == null ? null : uxtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uxtype.uxtypeMark
     *
     * @return the value of t_uxtype.uxtypeMark
     *
     * @mbggenerated
     */
    public String getUxtypeMark() {
        return uxtypeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uxtype.uxtypeMark
     *
     * @param uxtypeMark the value for t_uxtype.uxtypeMark
     *
     * @mbggenerated
     */
    public void setUxtypeMark(String uxtypeMark) {
        this.uxtypeMark = uxtypeMark == null ? null : uxtypeMark.trim();
    }
}