package com.model;

import java.util.Date;

public class Uyijian {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianId
     *
     * @mbggenerated
     */
    private Integer uyijianId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianName
     *
     * @mbggenerated
     */
    private String uyijianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianMark
     *
     * @mbggenerated
     */
    private String uyijianMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianMark1
     *
     * @mbggenerated
     */
    private String uyijianMark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianMark2
     *
     * @mbggenerated
     */
    private String uyijianMark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianImg
     *
     * @mbggenerated
     */
    private String uyijianImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianImgName
     *
     * @mbggenerated
     */
    private String uyijianImgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianDate
     *
     * @mbggenerated
     */
    private Date uyijianDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianZong
     *
     * @mbggenerated
     */
    private Integer uyijianZong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianZong1
     *
     * @mbggenerated
     */
    private Integer uyijianZong1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianZong2
     *
     * @mbggenerated
     */
    private Integer uyijianZong2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianDouble
     *
     * @mbggenerated
     */
    private Double uyijianDouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianDouble1
     *
     * @mbggenerated
     */
    private Double uyijianDouble1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianDouble2
     *
     * @mbggenerated
     */
    private Double uyijianDouble2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianType
     *
     * @mbggenerated
     */
    private Integer uyijianType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianType1
     *
     * @mbggenerated
     */
    private Integer uyijianType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uyijianType2
     *
     * @mbggenerated
     */
    private Integer uyijianType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uxtypeId
     *
     * @mbggenerated
     */
    private Integer uxtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.uxtypeName
     *
     * @mbggenerated
     */
    private String uxtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.bumenId
     *
     * @mbggenerated
     */
    private Integer bumenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.bumenName
     *
     * @mbggenerated
     */
    private String bumenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.buyuanId
     *
     * @mbggenerated
     */
    private Integer buyuanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.buyuanName
     *
     * @mbggenerated
     */
    private String buyuanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.buzhiId
     *
     * @mbggenerated
     */
    private Integer buzhiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.buzhiName
     *
     * @mbggenerated
     */
    private String buzhiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uyijian.roleName
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianId
     *
     * @return the value of t_uyijian.uyijianId
     *
     * @mbggenerated
     */
    public Integer getUyijianId() {
        return uyijianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianId
     *
     * @param uyijianId the value for t_uyijian.uyijianId
     *
     * @mbggenerated
     */
    public void setUyijianId(Integer uyijianId) {
        this.uyijianId = uyijianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianName
     *
     * @return the value of t_uyijian.uyijianName
     *
     * @mbggenerated
     */
    public String getUyijianName() {
        return uyijianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianName
     *
     * @param uyijianName the value for t_uyijian.uyijianName
     *
     * @mbggenerated
     */
    public void setUyijianName(String uyijianName) {
        this.uyijianName = uyijianName == null ? null : uyijianName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianMark
     *
     * @return the value of t_uyijian.uyijianMark
     *
     * @mbggenerated
     */
    public String getUyijianMark() {
        return uyijianMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianMark
     *
     * @param uyijianMark the value for t_uyijian.uyijianMark
     *
     * @mbggenerated
     */
    public void setUyijianMark(String uyijianMark) {
        this.uyijianMark = uyijianMark == null ? null : uyijianMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianMark1
     *
     * @return the value of t_uyijian.uyijianMark1
     *
     * @mbggenerated
     */
    public String getUyijianMark1() {
        return uyijianMark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianMark1
     *
     * @param uyijianMark1 the value for t_uyijian.uyijianMark1
     *
     * @mbggenerated
     */
    public void setUyijianMark1(String uyijianMark1) {
        this.uyijianMark1 = uyijianMark1 == null ? null : uyijianMark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianMark2
     *
     * @return the value of t_uyijian.uyijianMark2
     *
     * @mbggenerated
     */
    public String getUyijianMark2() {
        return uyijianMark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianMark2
     *
     * @param uyijianMark2 the value for t_uyijian.uyijianMark2
     *
     * @mbggenerated
     */
    public void setUyijianMark2(String uyijianMark2) {
        this.uyijianMark2 = uyijianMark2 == null ? null : uyijianMark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianImg
     *
     * @return the value of t_uyijian.uyijianImg
     *
     * @mbggenerated
     */
    public String getUyijianImg() {
        return uyijianImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianImg
     *
     * @param uyijianImg the value for t_uyijian.uyijianImg
     *
     * @mbggenerated
     */
    public void setUyijianImg(String uyijianImg) {
        this.uyijianImg = uyijianImg == null ? null : uyijianImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianImgName
     *
     * @return the value of t_uyijian.uyijianImgName
     *
     * @mbggenerated
     */
    public String getUyijianImgName() {
        return uyijianImgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianImgName
     *
     * @param uyijianImgName the value for t_uyijian.uyijianImgName
     *
     * @mbggenerated
     */
    public void setUyijianImgName(String uyijianImgName) {
        this.uyijianImgName = uyijianImgName == null ? null : uyijianImgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianDate
     *
     * @return the value of t_uyijian.uyijianDate
     *
     * @mbggenerated
     */
    public Date getUyijianDate() {
        return uyijianDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianDate
     *
     * @param uyijianDate the value for t_uyijian.uyijianDate
     *
     * @mbggenerated
     */
    public void setUyijianDate(Date uyijianDate) {
        this.uyijianDate = uyijianDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianZong
     *
     * @return the value of t_uyijian.uyijianZong
     *
     * @mbggenerated
     */
    public Integer getUyijianZong() {
        return uyijianZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianZong
     *
     * @param uyijianZong the value for t_uyijian.uyijianZong
     *
     * @mbggenerated
     */
    public void setUyijianZong(Integer uyijianZong) {
        this.uyijianZong = uyijianZong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianZong1
     *
     * @return the value of t_uyijian.uyijianZong1
     *
     * @mbggenerated
     */
    public Integer getUyijianZong1() {
        return uyijianZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianZong1
     *
     * @param uyijianZong1 the value for t_uyijian.uyijianZong1
     *
     * @mbggenerated
     */
    public void setUyijianZong1(Integer uyijianZong1) {
        this.uyijianZong1 = uyijianZong1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianZong2
     *
     * @return the value of t_uyijian.uyijianZong2
     *
     * @mbggenerated
     */
    public Integer getUyijianZong2() {
        return uyijianZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianZong2
     *
     * @param uyijianZong2 the value for t_uyijian.uyijianZong2
     *
     * @mbggenerated
     */
    public void setUyijianZong2(Integer uyijianZong2) {
        this.uyijianZong2 = uyijianZong2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianDouble
     *
     * @return the value of t_uyijian.uyijianDouble
     *
     * @mbggenerated
     */
    public Double getUyijianDouble() {
        return uyijianDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianDouble
     *
     * @param uyijianDouble the value for t_uyijian.uyijianDouble
     *
     * @mbggenerated
     */
    public void setUyijianDouble(Double uyijianDouble) {
        this.uyijianDouble = uyijianDouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianDouble1
     *
     * @return the value of t_uyijian.uyijianDouble1
     *
     * @mbggenerated
     */
    public Double getUyijianDouble1() {
        return uyijianDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianDouble1
     *
     * @param uyijianDouble1 the value for t_uyijian.uyijianDouble1
     *
     * @mbggenerated
     */
    public void setUyijianDouble1(Double uyijianDouble1) {
        this.uyijianDouble1 = uyijianDouble1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianDouble2
     *
     * @return the value of t_uyijian.uyijianDouble2
     *
     * @mbggenerated
     */
    public Double getUyijianDouble2() {
        return uyijianDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianDouble2
     *
     * @param uyijianDouble2 the value for t_uyijian.uyijianDouble2
     *
     * @mbggenerated
     */
    public void setUyijianDouble2(Double uyijianDouble2) {
        this.uyijianDouble2 = uyijianDouble2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianType
     *
     * @return the value of t_uyijian.uyijianType
     *
     * @mbggenerated
     */
    public Integer getUyijianType() {
        return uyijianType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianType
     *
     * @param uyijianType the value for t_uyijian.uyijianType
     *
     * @mbggenerated
     */
    public void setUyijianType(Integer uyijianType) {
        this.uyijianType = uyijianType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianType1
     *
     * @return the value of t_uyijian.uyijianType1
     *
     * @mbggenerated
     */
    public Integer getUyijianType1() {
        return uyijianType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianType1
     *
     * @param uyijianType1 the value for t_uyijian.uyijianType1
     *
     * @mbggenerated
     */
    public void setUyijianType1(Integer uyijianType1) {
        this.uyijianType1 = uyijianType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uyijianType2
     *
     * @return the value of t_uyijian.uyijianType2
     *
     * @mbggenerated
     */
    public Integer getUyijianType2() {
        return uyijianType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uyijianType2
     *
     * @param uyijianType2 the value for t_uyijian.uyijianType2
     *
     * @mbggenerated
     */
    public void setUyijianType2(Integer uyijianType2) {
        this.uyijianType2 = uyijianType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uxtypeId
     *
     * @return the value of t_uyijian.uxtypeId
     *
     * @mbggenerated
     */
    public Integer getUxtypeId() {
        return uxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uxtypeId
     *
     * @param uxtypeId the value for t_uyijian.uxtypeId
     *
     * @mbggenerated
     */
    public void setUxtypeId(Integer uxtypeId) {
        this.uxtypeId = uxtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.uxtypeName
     *
     * @return the value of t_uyijian.uxtypeName
     *
     * @mbggenerated
     */
    public String getUxtypeName() {
        return uxtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.uxtypeName
     *
     * @param uxtypeName the value for t_uyijian.uxtypeName
     *
     * @mbggenerated
     */
    public void setUxtypeName(String uxtypeName) {
        this.uxtypeName = uxtypeName == null ? null : uxtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.userId
     *
     * @return the value of t_uyijian.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.userId
     *
     * @param userId the value for t_uyijian.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.userName
     *
     * @return the value of t_uyijian.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.userName
     *
     * @param userName the value for t_uyijian.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.bumenId
     *
     * @return the value of t_uyijian.bumenId
     *
     * @mbggenerated
     */
    public Integer getBumenId() {
        return bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.bumenId
     *
     * @param bumenId the value for t_uyijian.bumenId
     *
     * @mbggenerated
     */
    public void setBumenId(Integer bumenId) {
        this.bumenId = bumenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.bumenName
     *
     * @return the value of t_uyijian.bumenName
     *
     * @mbggenerated
     */
    public String getBumenName() {
        return bumenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.bumenName
     *
     * @param bumenName the value for t_uyijian.bumenName
     *
     * @mbggenerated
     */
    public void setBumenName(String bumenName) {
        this.bumenName = bumenName == null ? null : bumenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.buyuanId
     *
     * @return the value of t_uyijian.buyuanId
     *
     * @mbggenerated
     */
    public Integer getBuyuanId() {
        return buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.buyuanId
     *
     * @param buyuanId the value for t_uyijian.buyuanId
     *
     * @mbggenerated
     */
    public void setBuyuanId(Integer buyuanId) {
        this.buyuanId = buyuanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.buyuanName
     *
     * @return the value of t_uyijian.buyuanName
     *
     * @mbggenerated
     */
    public String getBuyuanName() {
        return buyuanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.buyuanName
     *
     * @param buyuanName the value for t_uyijian.buyuanName
     *
     * @mbggenerated
     */
    public void setBuyuanName(String buyuanName) {
        this.buyuanName = buyuanName == null ? null : buyuanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.buzhiId
     *
     * @return the value of t_uyijian.buzhiId
     *
     * @mbggenerated
     */
    public Integer getBuzhiId() {
        return buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.buzhiId
     *
     * @param buzhiId the value for t_uyijian.buzhiId
     *
     * @mbggenerated
     */
    public void setBuzhiId(Integer buzhiId) {
        this.buzhiId = buzhiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.buzhiName
     *
     * @return the value of t_uyijian.buzhiName
     *
     * @mbggenerated
     */
    public String getBuzhiName() {
        return buzhiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.buzhiName
     *
     * @param buzhiName the value for t_uyijian.buzhiName
     *
     * @mbggenerated
     */
    public void setBuzhiName(String buzhiName) {
        this.buzhiName = buzhiName == null ? null : buzhiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.roleId
     *
     * @return the value of t_uyijian.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.roleId
     *
     * @param roleId the value for t_uyijian.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uyijian.roleName
     *
     * @return the value of t_uyijian.roleName
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uyijian.roleName
     *
     * @param roleName the value for t_uyijian.roleName
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}